### ISSUE TITLE
certificate verify failed (Faraday::SSLError)

### ISSUE THREAD

**Issue by keenam** [will-in-wi/letsencrypt-webfaction#1]
Hello,
I would like to ask if you would please assist with the following error:

    [me@web504 my-scripts]$ letsencrypt_webfaction --contact me@gmail.com --domains cloud.me.com --public ~/webapps/owncloud/htdocs/
    /home/me/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (Faraday::SSLError)
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1398:in `request'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `head'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday.rb:99:in `method_missing'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/acme-client-0.3.0/lib/acme/client/faraday_middleware.rb:92:in `get_nonce'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/acme-client-0.3.0/lib/acme/client/faraday_middleware.rb:85:in `pop_nonce'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/acme-client-0.3.0/lib/acme/client/faraday_middleware.rb:11:in `call'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/acme-client-0.3.0/lib/acme/client.rb:25:in `register'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/letsencrypt_webfaction-0.0.2/lib/letsencrypt_webfaction/application.rb:65:in `register_key!'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/letsencrypt_webfaction-0.0.2/lib/letsencrypt_webfaction/application.rb:20:in `run!'
        from /home/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/letsencrypt_webfaction-0.0.2/exe/letsencrypt_webfaction:5:in `<top (required)>'
        from /home/me/.rbenv/versions/2.3.0/bin/letsencrypt_webfaction:23:in `load'
        from /home/me/.rbenv/versions/2.3.0/bin/letsencrypt_webfaction:23:in `<main>'
    [me@web504 my-scripts]$

Thank you!

**Comment by will-in-wi** [comment]
Thanks for the report! Could you post the output of running `curl -v https://acme-v01.api.letsencrypt.org/` on your server? I only have access to the Centos6 WebFaction servers, and it looks like you are on Centos7, so I wonder whether there is a difference somewhere.

**Comment by keenam** [comment]
I am indeed on a newer WF server, and following is the output of command you mentioned:

[me@web504 ~]$ curl -v https://acme-v01.api.letsencrypt.org/
*   Trying 2a02:26f0:7b:185::3d5...
* Connected to acme-v01.api.letsencrypt.org (2a02:26f0:7b:185::3d5) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*    subject: CN=*.api.letsencrypt.org; O=INTERNET SECURITY RESEARCH GROUP; L=Mountain View; ST=California; C=US
*    start date: Jun 26 17:05:45 2015 GMT
*    expire date: Jun 25 17:05:45 2018 GMT
*    subjectAltName: acme-v01.api.letsencrypt.org matched
*    issuer: C=US; O=IdenTrust; OU=TrustID Server; CN=TrustID Server CA A52
*    SSL certificate verify ok.
> GET / HTTP/1.1
> Host: acme-v01.api.letsencrypt.org
> User-Agent: curl/7.47.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: text/html
< Content-Length: 2175
< Last-Modified: Tue, 13 Oct 2015 15:42:36 GMT
< ETag: "561d266c-87f"
< X-Frame-Options: DENY
< Strict-Transport-Security: max-age=604800
< Accept-Ranges: bytes
< Expires: Tue, 23 Feb 2016 16:16:05 GMT
< Cache-Control: max-age=0, no-cache, no-store
< Pragma: no-cache
< Date: Tue, 23 Feb 2016 16:16:05 GMT
< Connection: keep-alive
<
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content=
  "width=device-width, initial-scale=1">

  <title>Boulder: The Let's Encrypt CA</title>
  <link href=
  "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
  rel="stylesheet" type="text/css">
  <link href=
  "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"
  rel="stylesheet" type="text/css">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-6 text-right">
        <p style="font-size: 90px;">
        <i class="fa fa-barcode"></i></p>
      </div>

      <div class="col-xs-6 text-left">
        <h1>Boulder<br>
        <small>The Let's Encrypt CA</small></h1>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-8 col-xs-offset-2 text-center">
        <h3>This is an <a href="https://github.com/letsencrypt/acme-spec/">ACME</a> Certificate Authority running <a href="https://github.com/letsencrypt/boulder">Boulder</a>.</h3>
        <p>This is a <em>programmatic</em> endpoint, an API for a computer to talk to. You should probably be using a specialized client to utilize the service, and not your web browser. See <a href="https://letsencrypt.org/"><tt>https://letsencrypt.org/</tt></a> for help.</p>
        <p>If you're trying to use this service, note that the starting point, <em>the directory</em>, is available at this URL: <a href="https://acme-v01.api.letsencrypt.org/directory"><tt>https://acme-v01.api.letsencrypt.org/directory</a></tt>.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4 col-xs-offset-2 text-center">
        <p><a href="https://letsencrypt.status.io" title="Twitter">
          <i class="fa fa-area-chart"></i>
          Service Status (letsencrypt.status.io)
        </a></p>
      </div>
      <div class="col-xs-4 text-center">
        <p><a href="https://twitter.com/letsencrypt" title="Twitter">
          <i class="fa fa-twitter"></i>
          Check with us on Twitter
        </a></p>
      </div>
    </div> 
  </div>


</body>
</html>
* Connection #0 to host acme-v01.api.letsencrypt.org left intact
[me@web504 ~]$

**Comment by will-in-wi** [comment]
That looks just as expected. I've sent a request to Webfaction for short term access to a newer server to see if I can reproduce this. I'll follow up to this ticket with the results.

If you feel ambitious (and know some Ruby), I'd suggest trying to check out the repo and using the Pry debugger to take a look at the exact cert message. Make sure that you use the stage LE server per the readme so that you don't get locked out for a week.

**Comment by keenam** [comment]
Thank you for looking into this!
I'm not great with programming languages at all, so I'll wait for further updates and please let me know if I can help with the current issue any further.

**Comment by will-in-wi** [comment]
Sounds good! Thanks for your patience. This is a fairly new utility, so I'm still hammering out the issues like this one.

**Comment by will-in-wi** [comment]
I got access to a newer server, but am unable to easily reproduce. Could I get you to try a couple of things?

First, could I get the output of `echo $SSL_CERT_FILE`?

Second, could you try running `SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt letsencrypt_webfaction [remainder of arguments]`?

Thanks!

**Comment by keenam** [comment]
Hello!

First command results in a blank output, and the second one results in the following:

https://gist.github.com/keenam/9c55a664d9739bd3e921

**Comment by will-in-wi** [comment]
The second command looks much better. Now it is failing to verify the domain.

The client is creating a folder called .well-known in the public directory. Could you verify that this file is accessible from the broader internet?

**Comment by keenam** [comment]
I made sure that there is access from the internet and now the get the following output on 2md command:

LetsEncrypt Webfaction has generated a new certificate for me.com. The certificates have been placed in /home/me/le_certs/me.com/20160224143346. You now need to request installation from the WebFaction support team.

Go to https://help.webfaction.com, log in, and paste the following text into a new ticket:

Please apply the new certificate in /home/me/le_certs/me.com/20160224143346 to me.com. Thanks!


Using the command without the preceding "SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt" still presents the same error.

**Comment by will-in-wi** [comment]
Then you are good to go! Just make sure that you prepend that environment variable to any cron jobs. I'll add a note to the readme about this.

Thanks!

**Comment by will-in-wi** [comment]
For future reference, I've added troubleshooting steps here: https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Troubleshooting

**Comment by will-in-wi** [comment]
@keenam did this work for you in the end?
