### ISSUE TITLE
uninitialized constant OpenSSL::PKey::EC error

### ISSUE THREAD

**Issue by ryanseddon** [will-in-wi/letsencrypt-webfaction#10]
Hi, I've followed the instructions to get this setup but when I try to run the command I get the following error.

```bash
[username@web123 ~]$ letsencrypt_webfaction --config ~/le_config.yml
/home/username/.letsencrypt_webfaction/gems/gems/json-jwt-1.5.2/lib/json/jwk/jwkizable.rb:69:in `<top (required)>': uninitialized constant OpenSSL::PKey::EC (NameError)
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/username/.letsencrypt_webfaction/gems/gems/json-jwt-1.5.2/lib/json/jwt.rb:102:in `<top (required)>'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/username/.letsencrypt_webfaction/gems/gems/acme-client-0.3.0/lib/acme-client.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/username/.letsencrypt_webfaction/gems/gems/acme-client-0.3.0/lib/acme/client.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/username/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.0.0/lib/letsencrypt_webfaction/application.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/username/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.0.0/exe/letsencrypt_webfaction:3:in `<top (required)>'
	from /home/username/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/username/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

I also can't seem to install any ruby version via rbenv? Any pointers?

**Comment by will-in-wi** [comment]
The problem is that you are probably using a [CentOS 5 box](https://docs.webfaction.com/user-guide/server.html#finding-your-server-s-operating-system). It has an older version of OpenSSL which doesn't support the Elliptic Curve (EC) Algorithm which json-jwt depends on. This is why the Readme says:

> The CentOS 5 systems do not have a new enough OpenSSL to include the algorithms required. You may be able to make this work using rbenv and compiling openssl yourself.

I want to put together a tutorial for compiling a custom OpenSSL for CentOS 5 and then using RBenv to make this work, but I haven't had time yet.

If your server is not <= web299 and <= dweb88, please let me know. it may be another issue I'm not yet aware of.

**Comment by ryanseddon** [comment]
Yeah my server is <web299 so seems to be that issue, I did try and build a local copy of openssl in my home directory but failed. Was following these [steps](https://github.com/magnumripper/JohnTheRipper/wiki/Howto-build-non-root-when-system-does-not-have-OpenSSL).

**Comment by will-in-wi** [comment]
I've built a first draft of a tutorial here: https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Install-custom-OpenSSL-and-Ruby-on-CentOS-5-host

However, I haven't yet been successful in getting RBEnv to use my custom OpenSSL.

**Comment by will-in-wi** [comment]
I just got it to work and modified the instructions.

**Comment by ryanseddon** [comment]
Great thanks those steps worked but I'm still getting the same error when I run `letsencrypt_webfaction --config ~/config.yml`?

**Comment by will-in-wi** [comment]
What's the output of `type letsencrypt_webfaction`?

**Comment by will-in-wi** [comment]
And `type ruby` and `ruby -ropenssl -e "puts OpenSSL::PKey::EC"`?

**Comment by ryanseddon** [comment]
```bash
[username@webxxx ~]$ type letsencrypt_webfaction
letsencrypt_webfaction is a function
letsencrypt_webfaction ()
{
    PATH=$PATH:$GEM_HOME/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction $*
}
```

```bash
[username@webxxx ~]$ type ruby
ruby is /usr/local/bin/ruby
[username@webxxx ~]$ rbenv local
2.2.4
```

```bash
[username@webxxx ~]$ ruby -ropenssl -e "puts OpenSSL::PKey::EC"
-e:1: uninitialized constant OpenSSL::PKey::EC (NameError)
```

**Comment by ryanseddon** [comment]
I feel like this may be in a weird state from me trying to use system ruby first and then trying rbenv

**Comment by will-in-wi** [comment]
For me, `type ruby` returns `/home/myuser/.rbenv/shims/ruby`

I'm guessing that you either need to restart your shell or add `eval "$(rbenv init -)"` to your `.bash_profile`.

**Comment by ryanseddon** [comment]
Got it! 

I deleted letsencrypt_webfaction function from `.bash_profile` and then did a `gem install letsencrypt_webfaction` once my ruby was pointing to the right location.

I had to also do this so as not to get an SSL error https://github.com/google/google-api-ruby-client/issues/235#issuecomment-169956795 

Thanks a lot for your help!

**Comment by will-in-wi** [comment]
Wonderful! Glad to hear it worked.
