### ISSUE TITLE
Invalid response | Make sure that you can access http://sitename.nl/.well-known/acme-challenge/

### ISSUE THREAD

**Issue by DreeOlee** [will-in-wi/letsencrypt-webfaction#100]
Hello,

I get the folowing error:

Failed to verify statuses.
metics.nl: Invalid response from http://metics.nl/.well-known/acme-challenge/
Make sure that you can access http://metics.nl/.well-known/acme-challenge/

Can you help me?

**Comment by DreeOlee** [comment]
![image](https://user-images.githubusercontent.com/32505667/31664779-19c94ad0-b347-11e7-8674-f22c5e96ba77.png)

**Comment by will-in-wi** [comment]
Is there more to the URL?

I'd expect the url to be something like `http://metics.nl/.well-known/acme-challenge/alongstringofcharacters`

**Comment by DreeOlee** [comment]
Yeah there is. This is the complete syntax

<pre><code>Failed to verify statuses.
metics.nl: Invalid response from http://metics.nl/.well-known/acme-challenge/Q0Lb98NA9LI4nDb1NJ_s_YPrzjL6OsciN7ysQf4JIEc: "<h1>Not Found</h1><p>The requested URL /.well-known/acme-challenge/Q0Lb98NA9LI4nDb1NJ_s_YPrzjL6OsciN7ysQf4JIEc was not found on "
Make sure that you can access http://metics.nl/.well-known/acme-challenge/Q0Lb98NA9LI4nDb1NJ_s_YPrzjL6OsciN7ysQf4JIEc
www.metics.nl: Invalid response from http://www.metics.nl/.well-known/acme-challenge/eVBld8w1UebHueqsffHuKok1Aov6EQP_zwUnQMZTxMg: "<h1>Not Found</h1><p>The requested URL /.well-known/acme-challenge/eVBld8w1UebHueqsffHuKok1Aov6EQP_zwUnQMZTxMg was not found on "
Make sure that you can access http://www.metics.nl/.well-known/acme-challenge/eVBld8w1UebHueqsffHuKok1Aov6EQP_zwUnQMZTxMg
</code></pre>

**Comment by DreeOlee** [comment]
tried differtent things but can't get it up and running. Also tried this: [Webfaction LetsEncrypt Django](https://manikos.github.io/webfaction-letsencrypt-django) but there I got stucked on point 15. Could it be something in the url's ?

**Comment by DreeOlee** [comment]
Everything seems oké, but can't reach the file through the link in the chrome browser
Also removed the redirect to https.....maybe that is interfering. but also no result

Does anyone have a glue what is happening here? (tried this for 777 and 755 permissions)

The site is working now, but not safe. www.metics.nl

![acme-challange-problem-1](https://user-images.githubusercontent.com/32505667/31707719-64a709ec-b3ed-11e7-9329-408442c82bb7.png)
![acme-challange-problem-2](https://user-images.githubusercontent.com/32505667/31707721-64eadf28-b3ed-11e7-8e76-823f691aa661.png)

**Comment by will-in-wi** [comment]
I don't personally know Django very well. I'm guessing that `~/webapps/metics` is not serving on `www.metics.nl`. You may need to configure the http domain to serve the `.well-known` directory and redirect for everything else.

**Comment by ElectricFeet** [comment]
I was able to access metics.nl via https and http, so it looks like this is solved.

**Comment by josuevalrob** [comment]
I had the same problem.. in the config params, didn't include the correct _site folder._  I hope this help somebody.
