### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by nootrope** [will-in-wi/letsencrypt-webfaction#101]
How advisable is it to wipe the slate by deleting everything (except for the key file) related to a broken domain in `~/certificates` and `~/webapps/AFFECTED_APP/.well-known/acme-challenge/` and rerun the same CLI command (which worked otherwise for 2 other domains)?

**Comment by will-in-wi** [comment]
Deleting shouldn't matter.

At least for me, everything in `~/certificates` is owned read-only by root, and you can't delete directly anyway, other than by using the admin interface.

The contents of any particular `.well-known` directory are only used once for a particular validation and can be safely deleted after that.

**Comment by nootrope** [comment]
Thank you for the insight! Could have sworn I ended up deleting one or more of the old challenge endpoints and thought that was what broke TLS.

My issue was cosmetically sorted out by trying many permutations of CloudFlare settings but it means I ended up with a CloudFlare cert. To be clear, if I want to start anew for the problem domain, would I delete all the above files (via a support ticket if necessary), and ask support to also remove the cert wherever it lives in admin space? Or would asking them to delete that cert be sufficient? Sorry I do not know enough Ruby to divine what all you're doing with your excellent resource.

**Comment by will-in-wi** [comment]
If you are starting over, you can delete all the relevant certificates from the admin interface. You can choose to delete the contents of the various `.well-known` directories, but it will not effect the system positively or negatively.
