### ISSUE TITLE
WebFaction API username, password, and/or servername are incorrect. Login failed

### ISSUE THREAD

**Issue by pastonchase** [will-in-wi/letsencrypt-webfaction#105]
Hi
I'm using letsencrypt_webfaction 2.2.1 and failing with:
WebFaction API username, password, and/or servername are incorrect. Login failed

I've been in contact with Webfaction support who confirm I'm using the correct API username, password and severname are correct and suggest going back to an earlier version of letsencrypt_webfaction.

The command I'm using is as follows (together with the error message) although I've obviously changed some of the parameter values for security.

Is it possible to get an earlier version (webfaction suggest 2.0.1), or is that not the way to go?

letsencrypt_webfaction --letsencrypt_account_email support@paston.co.uk --domains domain.co.uk,www.domain.co.uk --public /home/paston4/webapps/proof/wp-content --username <username> --password <password> --servername web123
WebFaction API username, password, and/or servername are incorrect. Login failed

**Comment by pastonchase** [comment]
There was an error in the command - it should have read:
> letsencrypt_webfaction --letsencrypt_account_email support@paston.co.uk --domains www.lcolm.co.uk,lcolm.co.uk --public /home/paston4/webapps/proof/ --username <username> --password <password> --servername web123

**Comment by ElectricFeet** [comment]
You don't need `--servername`. Not sure why. Someone had the same issue in #82 .

Perhaps @will-in-wi  could comment on when `--servername` is actually needed.

As you're using WordPress, you may be interested in [a guide I wrote in the wiki](https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Easy-WordPress-walkthrough-for-Let'sEncrypt)

**Comment by will-in-wi** [comment]
Servername shouldn't be needed under normal circumstances, as we lookup the name of the system on which the app is running: https://github.com/will-in-wi/letsencrypt-webfaction/blob/master/lib/letsencrypt_webfaction/args_parser.rb#L134

You listed your command as:

```
letsencrypt_webfaction --letsencrypt_account_email support@paston.co.uk --domains www.lcolm.co.uk,lcolm.co.uk --public /home/paston4/webapps/proof/ --username --password --servername web123
```

A couple of questions/comments:
* As previously mentioned, you should be able to drop servername.
* Are you literally using `--username --password`, or something like `--username myuser --password mypass`? If the former, then you are passing a nil username and a nil password, which might explain your issue.

**Comment by pastonchase** [comment]
Thanks for the comments - actually got it working about 1 hour ago using the following:

letsencrypt_webfaction --letsencrypt_account_email support@paston.co.uk --domains www.lcolm.co.uk,lcolm.co.uk --public /home/paston4/webapps/proof/ --username 'myusername' --password 'mypassword' --servername 'Web123'

It seems it needed the single quotes around the username/password and servername making those bits of data strings

**Comment by will-in-wi** [comment]
Makes sense. I'm glad you got it working!
