### ISSUE TITLE
WebFaction API username, password, and/or servername are incorrect. Login failed.

### ISSUE THREAD

**Issue by vrghost242** [will-in-wi/letsencrypt-webfaction#109]
Noticed someone had had the same issue as me, but could not get the same solution to work. 
Using the same username and password as I use to log into the webfaction control center, I issue the following line 

```
letsencrypt_webfaction --letsencrypt_account_email admin@10togive.org --domains www.10togive.org,10togive.org,api.10togive.org,app.10togive.org,compass.10togive.org --public /home/myusername/webapps/10togive_wp  --username 'myusername' --password 'mypassword'
```
I also tried by adding 
`--servername 'web123'` and `--servename 'web123.webfaction.com'`

Still get 
> WebFaction API username, password, and/or servername are incorrect. Login failed.

**Comment by will-in-wi** [comment]
Generally (always?), you don't need the `servername` param, as it will autodetect the server.

Does your password have any special characters which might cause issues in Bash?

**Comment by vrghost242** [comment]
Problem solved, and hate to say what it was, but it is Friday afternoon so.
Used the wrong password, somehow the one keychain shower me was the old one. So very very sorry about that.

**Comment by will-in-wi** [comment]
Glad to hear you got it working!
