### ISSUE TITLE
Suggestions with auto built static website

### ISSUE THREAD

**Issue by vallieres** [will-in-wi/letsencrypt-webfaction#110]
Hi,

I would like I use your tool but I have an audeploying workflow and I’m not sure how to proceed.

I have a website called app_git which receives a push event when I commit a new change and it triggers à Jekyll build and rsyncs it to the app folder.

Right now your tool works but moves the well-known folder to the destination folder and when the next commit is pushed, it will remove the files.

Do you have a suggestion short of doing the work manually every 2 months and commiting the changes?

**Comment by d3cline** [comment]
Add some stuff to your hook which moves it back.

**Comment by will-in-wi** [comment]
Or ignore the well-known dir in your rsync command.

**Comment by will-in-wi** [comment]
Although the file only has to exist briefly while the domain is validated. So as long as you don't do a deploy during revalidation, it's probably fine for that folder to get deleted on deploy.

**Comment by vallieres** [comment]
Thanks! I did not know it only had to live a short time. I thought it needed to be validated regularly.
Since I'm planning to renew the certs during the night, and I don't publish many articles while I sleep, it will live there at the very least a few hours so I should be good!

Thanks for your help!
