### ISSUE TITLE
Suddenly doesn't work to create new cert? Renewing works fine

### ISSUE THREAD

**Issue by hrsetyono** [will-in-wi/letsencrypt-webfaction#111]
Hi, so I have the problem as stated in the title. All my newly created certificates always give "Privacy Error" page in Chrome and other browser even after few days.

My preferred method to get the cert is to create new YML files and call it via CLI

Sample Command: `letsencrypt_webfaction --config ~/le_config/mydomain.yml`

Sample YML:

```
key_size: 4096
# We need an ACME server to talk to, see github.com/letsencrypt/boulder
endpoint: 'https://acme-v01.api.letsencrypt.org/'
domains: ['mydomain.com', 'www.mydomain.com']
public: '~/webapps/mydomain/'
output_dir: '~/le_certs/'
letsencrypt_account_email: 'myemail@mydomain.com'
api_url: 'https://api.webfaction.com/'
username: 'myusername'
password: 'mypassword'
servername: ''
cert_name: ''
```

It always works great but suddenly the error happened. I tried 4 other new sites and all are invalid too.

Is there limit to the `account_email`? I'm 100% sure the username, password, public folder, and other settings are correct.

**Comment by will-in-wi** [comment]
Can you check to see what about the cert Chrome dislikes? Ssllabs.com or Firefox might also have more information.

**Comment by hrsetyono** [comment]
Hi, here's my ssllab result https://www.ssllabs.com/ssltest/analyze.html?d=thesyne.com&latest

It says certificate not valid for domain name, I have checked again and I typed the correct domain in my YML file

**Comment by hrsetyono** [comment]
I posted this in Webfaction forum and the support found that I use different IP for HTTP and HTTPS version.

I have changed it to be the same and it works.

Link to thread: https://community.webfaction.com/questions/21488/all-recent-lets-encrypt-certificate-are-invalid-old-one-works-fine

Thanks for your help
