### ISSUE TITLE
trying to get auto renew running for certs already installed

### ISSUE THREAD

**Issue by bonnysitesdotcom** [will-in-wi/letsencrypt-webfaction#115]
I am running ssh in Putty on windows, I don't see that it should affect anything, as that is how I got the certs installed in the first place.

In this tutorial, I get stuck at the 2nd step: "Add the following to ~/.bash_profile (using, for example, an FTP client or your favorite text editor): function letsencrypt_webfaction { PATH=$PATH:$GEM_HOME/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction $* } " 

What I get is: -bash: /home/<username>/.bash_profile: No such file or directory I assume that file SHOULD exist since it says "Add the following to..."? 

I believe I did something dumb when trying to run this back in November...I am not very familiar working with ssh but usually I can copy/paste. It's not working in this scenario however...
-- | --

**Comment by will-in-wi** [comment]
`/home//.bash_profile` would seem to indicate that the user is missing. I would expect it to be writing to a file like `/home/bonnysitesdotcom/.bash_profile`. Exactly what command are you running when you get that error? I personally use vim or nano, e.g. `nano ~/.bash_profile`.

**Comment by bonnysitesdotcom** [comment]
I didn't know what command to use to edit, so I just copied/pasted ~/.bash_profile to see what would happen.

**Comment by bonnysitesdotcom** [comment]
http://tldp.org/LDP/abs/html/sample-bashrc.html  seems like just a tad overkill...

**Comment by bonnysitesdotcom** [comment]
I tried nano ~/.bash_profile and it is making a new file. Can I do that safely?

**Comment by will-in-wi** [comment]
I'm mildly surprised that it is creating a new file. My default `~/.bash_profile` looks like
```bash
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH
```

But if you are creating a new `~/.bash_profile`, that's probably safe. You can paste the example code into there.

**Comment by bonnysitesdotcom** [comment]
Thanks so much!  To be honest, I think I may have deleted it in my earlier
try with letsencrypt-webfaction in Nov last year... or corrupted it.... my
memory fails me...

On Mon, Feb 26, 2018 at 10:42 PM, William Johnston <notifications@github.com

**Comment by bonnysitesdotcom** [comment]
Ok, now for the .py file, if I am reading correctly I need to configure in 2 areas, the variables such as server, cert name etc (4 item), and then the path in the following "paragraph".  My question is: for the {acme} part of the path, would that be the folder where acme.sh saves the certificates that I have downloaded and then uploaded to create the actual certificates in the webfaction panel? and domain is the folder name within {acme} that shows in sftp for that website?

**Comment by will-in-wi** [comment]
If you think you accidentally deleted your `~/.bash_profile`, you can restore it by running `cp /etc/skel/.bash_profile ~/.bash_profile`.

We might be talking about different things. `acme.sh` is an unrelated tool. Letsencrypt-webfaction has no `.py` files (python source files).

**Comment by bonnysitesdotcom** [comment]
I know about acme.sh and the profile being different things, and about the
python file, the file was included by someone as an auto-renew tool for
acme.sh

Unfortunately I am not familiar with python (yet) so I have a learning
curve ahead of me.

Thanks for all your help!

**Comment by will-in-wi** [comment]
Sorry for the slow response. I'm not referring to the difference between `.bash_profile` and `acme.sh`, but rather the difference between `acme.sh` and `letsencrypt_webfaction`. [`acme.sh`](https://github.com/Neilpang/acme.sh) is a different tool and a different way of approaching issuing Let's Encrypt certificates. If that's the tool you want to use, you'll want to go to them for support.

I can help with the `letsencrypt_webfaction` tool.

**Comment by bonnysitesdotcom** [comment]
Ah, gotcha, thanks!  I already have the certificates set up, and was able
to get letsencrypt_webfaction installed, but I couldn't get it to work to
install the certificates because of the ..bash_profile issue, couldn't get
past that...Is it possible to get it set up to just auto-renew what I have
already set up?

**Comment by will-in-wi** [comment]
> Is it possible to get it set up to just auto-renew what I have already set up?

As in, have `letsencrypt_webfaction` renew what `acme.sh` issued? Kind of, but you are essentially starting from scratch anyway. I'd just reissue the certs with `letsencrypt_webfaction` (or at least some of them), just so you know the automation works. Or wait until your currently issued certs are closer to expiration.

**Comment by webinventdotcom** [comment]
About the same issue (auto renew), are username and password really not needed for auto renews using a cron job ? It's just when we manually use the SSH tool, like the first time ?

**Comment by will-in-wi** [comment]
You do need the username and password for renewals, but that should be in the configuration file or the cron command.

**Comment by webinventdotcom** [comment]
Yes, that's what I thought, but this is the Cron example in the README.md on the main page https://github.com/will-in-wi/letsencrypt-webfaction

`# System Ruby Installation
0 4 1 */2 *     PATH=$PATH:$GEM_HOME/bin:/usr/local/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction --letsencrypt_account_email [you@youremail.com] --domains [yourdomain.com,www.yourdomain.com] --public ~/webapps/[yourapp/your_public_html]/ --quiet`

There is neither --username --password nor --config in this CRON renewal example
