### ISSUE TITLE
What does it mean if running letsencrypt_webfaction returns the following error

### ISSUE THREAD

**Issue by roytang** [will-in-wi/letsencrypt-webfaction#116]
ruby2.2: Is a directory -- /home/roytang/ (LoadError)

**Comment by will-in-wi** [comment]
Can you provide more of the command you are running?

**Comment by roytang** [comment]
Sorry, it's my fault, I had a typo in the function in .bash_profile T_T

**Comment by will-in-wi** [comment]
Glad to hear you got it working!

**Comment by roytang** [comment]
Yup, it works great! Thank you very much for this utility, it's much appreciated!
