### ISSUE TITLE
keep getting "letsencrypt_webfaction: command not found" error

### ISSUE THREAD

**Issue by abunur** [will-in-wi/letsencrypt-webfaction#121]
I previously successfully set up using SSL certificates using your instructions.  But I never set up the CRON job to automatically renew them so the certificates have now expired.  When I SSH into my Webfaction server though, any letsencrypt_webfaction command results in an error message, "letsencrypt_webfaction: command not found".  I went back and repeated the install instructions using:

GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem2.2 install letsencrypt_webfaction

After that, running letsencrypt_webfaction --version or letsencrypt_webfaction --help both result in the above error message.

I checked my .bash_profile and confirmed it contains the following:

function letsencrypt_webfaction {
    PATH=$PATH:$GEM_HOME/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction $*
}

I also ran source $HOME/.bash_profile but I still get the error message.

**Comment by abunur** [comment]
Guess I forgot this only works with your root account, not with an SSH account you create.

**Comment by will-in-wi** [comment]
That would be an interesting situation. Presumably, if you create an additional SSH account, you'd need to set up your bash profile on that account. You might be able to share the actual Gem installation. I've never tried it this way.
