### ISSUE TITLE
Too many registrations for this IP when trying to renew a cert

### ISSUE THREAD

**Issue by jnalanko** [will-in-wi/letsencrypt-webfaction#122]
Hi, I'm trying the renew my certificate using the same command I created it with. However, I get the following error:

`raise_on_error!': Error creating new registration :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/ (Acme::Client::Error::RateLimited)

I'm assuming there are other users at the same IP who have made so many registrations that the registration rate limit was hit. But I'm not trying to register a new account. I'm just trying to renew. I think this should not be subject to the registration rate limit. Is it the case that the code is sending a superfluous register-request even though it does not have to?

**Comment by will-in-wi** [comment]
I'm not sure which limit you are hitting. Could you post more of the error? That'll help me nail down which part of the codebase is impacted.

**Comment by jnalanko** [comment]
Sure:

/home/jnalanko/.letsencrypt_webfaction/gems/gems/acme-client-0.5.5/lib/acme/client/faraday_middleware.rb:43:in `raise_on_error!': Error creating new registration :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/ (Acme::Client::Error::RateLimited)
	from /home/jnalanko/.letsencrypt_webfaction/gems/gems/acme-client-0.5.5/lib/acme/client/faraday_middleware.rb:33:in `on_complete'
	from /home/jnalanko/.letsencrypt_webfaction/gems/gems/acme-client-0.5.5/lib/acme/client/faraday_middleware.rb:18:in `block in call'
	from /home/jnalanko/.letsencrypt_webfaction/gems/gems/faraday-0.13.1/lib/faraday/response.rb:61:in `on_complete'
	from /home/jnalanko/.letsencrypt_webfaction/gems/gems/acme-client-0.5.5/lib/acme/client/faraday_middleware.rb:18:in `call'
	from /home/jnalanko/.letsencrypt_webfaction/gems/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
	from /home/jnalanko/.letsencrypt_webfaction/gems/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
	from /home/jnalanko/.letsencrypt_webfaction/gems/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in `post'
	from /home/jnalanko/.letsencrypt_webfaction/gems/gems/acme-client-0.5.5/lib/acme/client.rb:45:in `register'
	from /home/jnalanko/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.2.1/lib/letsencrypt_webfaction/application.rb:70:in `register_key!'
	from /home/jnalanko/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.2.1/lib/letsencrypt_webfaction/application.rb:26:in `run!'
	from /home/jnalanko/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.2.1/exe/letsencrypt_webfaction:5:in `<top (required)>'
	from /home/jnalanko/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/jnalanko/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'

**Comment by will-in-wi** [comment]
We have to register a new private key before we can issue a cert with it. That's why it is running an additional registration call.

Are you using the default time in the cron example on the readme? If so, you might want to change that. There may be an issue with so may people on your server using this utility with the default renewal time that LE flags that particular IP. If you pick a different day, that may solve it.

**Comment by will-in-wi** [comment]
For example, if you are using `0 4 1 */2 *`, you might use `0 4 6 */2 *` to try on the 6th of the month instead of the 1st.

I find this utility useful for understanding cron syntax quickly: https://crontab.guru/#0_4_6_*/2_*

**Comment by jnalanko** [comment]
I didn't have a crontab entry yet. I tried manually a few times a couple of hours apart today. Then I installed a crontab to try on every 40th minute of an hour. Has not succeeded yet. The certificate is expiring in 8 days, so I'm slightly nervous :). Webfaction support said there really nothing to do except wait and try again.

So it seems there is a way to mess up everybody else's certificate renewals on the same IP by spamming requests. That sounds bad, but it seems it's not the fault of the script.

**Comment by jnalanko** [comment]
But really, legitimate renewals should not be turned down by the protocol. There is an exemption in the rules for renewals. Is it a flaw of the protocol, or is there a way to store the private key so it doesn't have to be registered each time?

**Comment by will-in-wi** [comment]
Yes, there is a DoS potential on shared hosts… I'm not sure what the answer to that is. Good question for LE.

It would be possible to request a new cert with the same private key, however, this is considered poor practice as compared to rotating the keys with each renewal. I'm not sure what CertBot does here…

I'll think about this and see if I can come up with a solution. I'd suggest pinging the LE community forum and see what they say. Feel free to link to this ticket, and please throw a link to the forum posting here if you make one. Thanks!

**Comment by jnalanko** [comment]
Still not working. I'm done with Let's Encrypt for now - I don't have time for this :). I went and bought a "real" certificate.

**Comment by jnalanko** [comment]
I still made the thread on the forums: https://community.letsencrypt.org/t/denial-of-service-attack-on-shared-hosts/59171

They say what you are doing is inadvisable.

**Comment by will-in-wi** [comment]
Splendid, thanks for asking the question! I'll respond there and figure out how to do this correctly.

**Comment by will-in-wi** [comment]
It looks like I'll need to introduce state tracking. When we set up for the first time, we create an account keypair and register using that. Subsequently, we generate additional private keys to create the CSRs.

This will be an API breaking change. I'll need to create a directory to store the state. Since this has been requested frequently, I'll probably also stop accepting tons of command line parameters and only use a single config file for all certs, which will track renewal. This is probably going to be version 3.0.0.

Depending on the timeline around #106, I will probably not make moving to the ACMEv2 API in scope for 3.0.0 since I don't want to delay this overmuch.

**Comment by will-in-wi** [comment]
The tricky part here is that we need to move everyone using <3 versions to >=3 once this is released. Otherwise old clients will continue to cause issues for new ones.

**Comment by will-in-wi** [comment]
If the WF support team is unable to help upgrade older clients, you may want to request a migration to a different host once v3 is out so that you are less likely to hit issues.

**Comment by will-in-wi** [comment]
The new design is confirmed. I'll start work.

**Comment by jnalanko** [comment]
Thank you very much!

**Comment by JacobOscarson** [comment]
Thanks a lot @will-in-wi for your work on this. It's a most valuable program, and I'd hope WebFaction gives you something in return.

**Comment by will-in-wi** [comment]
I just pushed out version 3.0.0 of this utility. It has a much better way of handling a lot of this and will hopefully be a lot more user friendly. It also solves the issue in this ticket. Please give it a shot and let me know if it works for you. I'll try to get bugs fixed promptly. Thanks!
