### ISSUE TITLE
Unable to renew certificate - undefined method `[]’ for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by manishh** [will-in-wi/letsencrypt-webfaction#124]
I am using letsencrypt-webfaction  for over a year now and the renewal is working fine with a cron job. The job ran successfully on 24th May and renewed another domain. However, it is failing now with the error shown, I have not made any changes to my config or cron job so far. I suspect this has something to do with recent GDPR changes, but not sure how to fix it. 

Any inputs, pointers would be highly appreciated.

Details --->
-------------------------------------------------------------------------------------------------------------------------------
I ran this command: `letsencrypt_webfaction --config ~/le_conf.yml --domains domain.com,www.domain.com --public <application_dir>`

It produced this output:

```
Failed to verify statuses.
<my_home>/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.1/lib/letsencrypt_webfaction/domain_validator.rb:65:in print_error': undefined method[]’ for nil:NilClass (NoMethodError)
from <my_home>/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.1/lib/letsencrypt_webfaction/domain_validator.rb:52:in block in print_errors' from <my_home>/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.1/lib/letsencrypt_webfaction/domain_validator.rb:52:ineach’
from <my_home>/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.1/lib/letsencrypt_webfaction/domain_validator.rb:52:in print_errors' from <my_home>/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.1/lib/letsencrypt_webfaction/domain_validator.rb:21:invalidate!’
from <my_home>/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.1/lib/letsencrypt_webfaction/application.rb:29:in run!' from <my_home>/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.1/exe/letsencrypt_webfaction:5:in<top (required)>’
from <my_home>/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in load' from <my_home>/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in’
```

**Comment by manishh** [comment]
I updated _letsencrypt-webfaction_ and tried again, but this is what I get - 

> Failed to verify statuses.
> domain.com: Still pending, but timed out
> www.domain.com: Still pending, but timed out

How do I renew my certificate now?

**Comment by will-in-wi** [comment]
What do you mean by recent GDPR fixes? Can you access the verification file externally?

**Comment by will-in-wi** [comment]
I just did a sizable upgrade of this utility in version 3.0. I'm not sure it'll fix your specific issue, but would you mind upgrading and letting me know if your issue still persists, with a new backtrace if so?

Thanks!

**Comment by manishh** [comment]
Most certainly, I'll try it right away!

**Comment by manishh** [comment]
Upgraded to v3.0, updated to newer config and ran the command, this is what I get :( 

```
~]$ letsencrypt_webfaction run
3 days until expiration of domain_com. Renewing...
Failed to verify statuses.
domain.com: Still pending, but timed out
www.domain.com: Still pending, but timed out
```

**Comment by manishh** [comment]
Here it is - 

```
# Your Webfaction username and password
username = "xxxxxx"
password = "yyyyyyyy"

# The email address which will be used to register with Let's Encrypt.
letsencrypt_account_email = "me@example.com"

# The ACME endpoint. Use the staging server until you get everything working.
# Then switch to the production endpoint.
endpoint = "https://acme-staging.api.letsencrypt.org/" # Staging
#endpoint = "https://acme-v01.api.letsencrypt.org/" # Production

# The URL to the WebFaction API. You should not change this under normal
# circumstances.
#api_url = "https://api.webfaction.com/"

# The hostname of the server you are on. Should be autodetected and not need to
# be changed.
#servername = "web123"

[[certificate]]
# The list of domains for which the cert should be issued. The first will be
# the common name.
domains = [
  "example.com",
  "www.example.com",
]

# Right now, only http01 is available. This is the default.
#method = "http01"

# The path to the root of your website. Can be an array as in the second example.
public = "~/webapps/zzzzzz"
# public = [
#   "~/webapps/myapp/public_html",
#   "~/webapps/myapp/public_html1",
# ]

# The name of your cert in the WebFaction admin interface. Will default to
# the cert common name with the dots replaced by underscores. (Optional)
# NOTE: If you change this and do not also rename it in the webfaction admin,
#       a new certificate will be issued.
name = "example_com"

# The size of the private key. 4096 is the default. You can use 2048.
#key_size = 4096
```

**Comment by will-in-wi** [comment]
Hmm… That looks reasonable…

The trouble is that right now there isn't much support in the client for listing why a domain failed to request validation. I'm wondering whether something about the domain is broken… But I don't know what without knowing the actual domain.

**Comment by manishh** [comment]
I should also add that I do see files with today's date under `https://www.my-domain.com/.well-known/acme-challenge/.`

Is there  something I can try/inspect directly myself?

**Comment by will-in-wi** [comment]
If I could reproduce this locally, I'd probably live-modify some of the underlying code to try and dump pieces of it.

I'm guessing that when this app calls `#request_verification` (https://github.com/unixcharles/acme-client/blob/acme-v1/lib/acme/client/resources/challenges/base.rb#L19), it's returning an unsuccessful response. I'd probably dump out (`puts response`) the response inside of `#request_verification`.

I'm happy to provide pointers if you want to dig in. It's a little more intensive Ruby debugging, so I can't entirely walk you through it.

**Comment by manishh** [comment]
Tried what you suggested and this is what I am getting - 

```
$ letsencrypt_webfaction run
3 days until expiration of mydomain_com. Renewing...
#<Faraday::Response:0x000000022002e0>
#<Faraday::Response:0x000000021a3040>
Failed to verify statuses.
mydomain.com: Still pending, but timed out
www.mydomain.com: Still pending, but timed out
```

Any other pointers?

**Comment by manishh** [comment]
This is with `puts response.inspect` - 

`#<Faraday::Response:0x0000000167f010 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body={"type"=>"http-01", "status"=>"pending", "uri"=>"https://acme-staging.api.letsencrypt.org/acme/challenge/7NQhC53da4sqRnMq_gOul05cJY4kMJLvSR06nwQ1FTY/134539789", "token"=>"6X9orxmfv-JK-arQO_QmqF69EgWjcMNp4N7MwsgZi-E", "keyAuthorization"=>"6X9orxmfv-JK-arQO_QmqF69EgWjcMNp4N7MwsgZi-E.9osb5Li67DhSWw8lTRE_DtZyWixHusl1HOwkJ-FxJ7U"} @url=#<URI::HTTPS https://acme-staging.api.letsencrypt.org/acme/challenge/7NQhC53da4sqRnMq_gOul05cJY4kMJLvSR06nwQ1FTY/134539789> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Acme::Client v0.6.3 (https://github.com/unixcharles/acme-client)"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x0000000167f010 ...> @response_headers={"server"=>"nginx", "content-type"=>"application/json", "content-length"=>"339", "boulder-requester"=>"6260979", "link"=>{"up"=>"https://acme-staging.api.letsencrypt.org/acme/authz/7NQhC53da4sqRnMq_gOul05cJY4kMJLvSR06nwQ1FTY"}, "location"=>"https://acme-staging.api.letsencrypt.org/acme/challenge/7NQhC53da4sqRnMq_gOul05cJY4kMJLvSR06nwQ1FTY/134539789", "replay-nonce"=>"UgZD49NaJIkzRS_Ov1MK5pPbJ6Giqo_nlhK_5C_Vd40", "expires"=>"Sun, 10 Jun 2018 17:32:28 GMT", "cache-control"=>"max-age=0, no-cache, no-store", "pragma"=>"no-cache", "date"=>"Sun, 10 Jun 2018 17:32:28 GMT", "connection"=>"close"} @status=202 @reason_phrase="Accepted">>
`

**Comment by will-in-wi** [comment]
202 Accepted is actually just fine… So it is successfully firing the request off…

I now think the issue is actually that it's timing out upstream. The error that comes back is "Remote PerformValidation RPCs failed". This is fired from here, upstream: https://github.com/letsencrypt/boulder/blob/master/va/va.go#L980

I got that from this part of the request:
https://acme-staging.api.letsencrypt.org/acme/challenge/7NQhC53da4sqRnMq_gOul05cJY4kMJLvSR06nwQ1FTY/134539789

Which returns
```json
{
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:serverInternal",
    "detail": "Remote PerformValidation RPCs failed",
    "status": 500
  },
  "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/7NQhC53da4sqRnMq_gOul05cJY4kMJLvSR06nwQ1FTY/134539789",
  "token": "6X9orxmfv-JK-arQO_QmqF69EgWjcMNp4N7MwsgZi-E",
  "keyAuthorization": "6X9orxmfv-JK-arQO_QmqF69EgWjcMNp4N7MwsgZi-E.9osb5Li67DhSWw8lTRE_DtZyWixHusl1HOwkJ-FxJ7U",
  "validationRecord": [
    {
      "url": "http://orisyssoft.com/.well-known/acme-challenge/6X9orxmfv-JK-arQO_QmqF69EgWjcMNp4N7MwsgZi-E",
      "hostname": "orisyssoft.com",
      "port": "80",
      "addressesResolved": [
        "119.81.68.111",
        "2401:c900:1101:143:31::71"
      ],
      "addressUsed": "119.81.68.111",
      "addressesTried": [
        "2401:c900:1101:143:31::71"
      ]
    },
    {
      "url": "http://www.orisyssoft.com/.well-known/acme-challenge/6X9orxmfv-JK-arQO_QmqF69EgWjcMNp4N7MwsgZi-E",
      "hostname": "www.orisyssoft.com",
      "port": "80",
      "addressesResolved": [
        "119.81.68.111",
        "2401:c900:1101:143:31::71"
      ],
      "addressUsed": "119.81.68.111",
      "addressesTried": [
        "2401:c900:1101:143:31::71"
      ]
    },
    {
      "url": "https://www.orisyssoft.com/.well-known/acme-challenge/6X9orxmfv-JK-arQO_QmqF69EgWjcMNp4N7MwsgZi-E",
      "hostname": "www.orisyssoft.com",
      "port": "443",
      "addressesResolved": [
        "119.81.68.111",
        "2401:c900:1101:143:31::71"
      ],
      "addressUsed": "119.81.68.111",
      "addressesTried": [
        "2401:c900:1101:143:31::71"
      ]
    }
  ]
}
```

At this point I'm stumped. Something about your webserver configuration is likely making it difficult or impossible for Let's Encrypt to connect. Or they are having an issue…

Could you open a ticket on their community support with the above URL, and linking to this ticket? Could you then add a new comment here with that ticket? They might be able to shed more light on the subject.

**Comment by manishh** [comment]
Done. I had already opened a ticket [there](https://community.letsencrypt.org/t/unable-to-renew-certificate-undefined-method-for-nil-nilclass-nomethoderror/63762) and I have added the details.

**Comment by will-in-wi** [comment]
LE has confirmed that it looks like a bug on their end. Right now, it is specific to the staging environment: https://github.com/letsencrypt/boulder/issues/3753
