### ISSUE TITLE
How to setup the Webfaction API config?

### ISSUE THREAD

**Issue by ericjames** [will-in-wi/letsencrypt-webfaction#129]
`WebFaction API username, password, and/or servername are incorrect. Login failed.`

The beginners guide says to setup a config.yml file which you can then point with letsencrypt_webfaction --config config.yml. This does not appear to work with Version 3.
http://bcc.npdoty.name/directions-to-migrate-your-WebFaction-site-to-HTTPS

I tried putting these values in the letsencrypt_webfaction.yml itself before [[certificate]] and it didn't do anything.

Let's get the instructions updated too once I get an answer.

**Comment by will-in-wi** [comment]
The yaml file isn't used anymore, and those instructions no longer apply to v3. You can see the upgrading doc to see how to handle that.

For future reference: those old instructions were referenced in https://github.com/will-in-wi/letsencrypt-webfaction/issues/21
