### ISSUE TITLE
Failed to verify statuses in 10 seconds. (RuntimeError)

### ISSUE THREAD

**Issue by ouchkernel** [will-in-wi/letsencrypt-webfaction#13]
Hey, 

Just wondering if you can help with the below error? I am running a static(Static only (no .htaccess)) webserver on Webfaction.

Thanks

```
$ letsencrypt_webfaction --account_email john@ouchkernel.com --domains ouchkernel.com,www.ouchkernel.com  --public ~/webapps/testapp
/home/ouchkernel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/letsencrypt_webfaction-1.0.1/lib/letsencrypt_webfaction/domain_validator.rb:22:in `validate!': Failed to verify statuses in 10 seconds. (RuntimeError)
	from /home/ouchkernel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/letsencrypt_webfaction-1.0.1/lib/letsencrypt_webfaction/application.rb:24:in `run!'
	from /home/ouchkernel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/letsencrypt_webfaction-1.0.1/exe/letsencrypt_webfaction:5:in `<top (required)>'
	from /home/ouchkernel/.rbenv/versions/2.3.0/bin/letsencrypt_webfaction:22:in `load'
	from /home/ouchkernel/.rbenv/versions/2.3.0/bin/letsencrypt_webfaction:22:in `<main>'
```

**Comment by will-in-wi** [comment]
Could you try the suggestions in here: https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Troubleshooting

If that doesn't help, please post back and we'll take a look.

Thanks!

**Comment by ouchkernel** [comment]
I actually found that late last night. I am trying to use Ghost which does not seem to have much in the way of static content. Step I took to get this to work.

- Removed Ghost from running website
- Created a "Static only (no .htaccess)" application
- Added "Static only (no .htaccess)" to the website
- Ran letsencrypt_webfaction (It worked)
- Removed "Static only (no .htaccess)"
- Added Ghost back

I think I am going to script this to wrap letsencrypt since there is an API that seems like it can do all these functions.

Thanks,

**Comment by will-in-wi** [comment]
Isn't Ghost a Node app? Does it have any way of serving flat files from the document root?

**Comment by ouchkernel** [comment]
I couldnt get it to work with how it was serving flat files. But I was able to create a separate static website(no secure) and run against that with the same domains. When that was done I just put a .htaccess file to redirect non-secure to the secure site. https://ouchkernel.com/2016/04/27/ghost-letsencrypt-webfaction/ is a quick post about it.

**Comment by will-in-wi** [comment]
Nice! So, if I understand correctly, the http site is serving the validations and the https site is serving ghost. The http site redirects all non-`.well-known` traffic to the https site.

I'll add this to the docs.

**Comment by will-in-wi** [comment]
https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Node-Ghost

**Comment by tyssen** [comment]
I'm getting this error too on a brand new Webfaction account. After running 

    letsencrypt_webfaction --account_email email@address.com --domains domain.com --public ~/webapps/production/www/

I get the error. 

`.well-known` is created in `www` but it only contains an `acme-challenge` folder which then contains files with long, random string file names.

**Comment by will-in-wi** [comment]
Could you try the troubleshooting steps here? https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Troubleshooting

If you still have issues, I'll take a shot at working through it.

**Comment by tyssen** [comment]
Sorry, forgot to set up the redirect from http to https first.
