### ISSUE TITLE
Invalid response

### ISSUE THREAD

**Issue by jenxi** [will-in-wi/letsencrypt-webfaction#130]
I'm getting the following error when I run `letsencrypt_webfaction run`

```
Invalid response from http://www.domain.com/.well-known/acme-challenge/QykNz4N2F5x7V3WxzxsNESfwHEZbumn-sGA_sk52kMI: "<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
  "http://www.w3.org/TR/html4/strict.dtd">`
`<html>`
  `<head>`
    `<meta http-equi"`
`Make sure that you can access http://www.domain/.well-known/acme-challenge/QykNz4N2F5x7V3WxzxsNESfwHEZbumn-sGA_sk52kMI
```

I can find the file via FTP and I can go directly to that URL in my browser.

**Comment by will-in-wi** [comment]
When you go directly to that URL, does it return the acme challenge file? I've run into issues occasionally where IPv6 isn't set up correctly and IPv4 returns the correct file.

**Comment by jenxi** [comment]
I get this: QykNz4N2F5x7V3WxzxsNESfwHEZbumn-sGA_sk52kMI.GFXSGlTs2NzaPYiB-J09Dx2LuaoXuzoLvPIwxOOAE8k

**Comment by ericdorsey** [comment]
@jenxi 
You did edit the `domains = ` array in the `letsencrypt_webfaction.toml` right?

**Comment by jenxi** [comment]
@ericdorsey Yes, I changed the error for posting publicly.

**Comment by will-in-wi** [comment]
I've seen this before. Occasionally, WF will get a server in an inconsistent state where the server will respond correctly to an ipv4 originating request, but will return a 404 to an ipv6 originating request. Most of us issue requests from ipv4, but LE uses ipv6.
