### ISSUE TITLE
Allow "force run" option

### ISSUE THREAD

**Issue by ericdorsey** [will-in-wi/letsencrypt-webfaction#132]
https://github.com/will-in-wi/letsencrypt-webfaction/blob/master/lib/letsencrypt_webfaction/application/run.rb#L66-L67

If you run `$ letsencrypt_webfaction run`, and the certificate is too new, letsencrypt webfaction will skip your command because there is no need to renew the certificate; which would normally make sense. However, ideally there would be an option to "force run anyway" (maybe `$ letsencrypt_webfaction run --force`) for when you need to overwrite the existing certificate.

This came up for me because I had initially installed a certificate using the staging site, and to get my live certificate (after I realized what had happened and changed to the production LetsEncrypt site in the config) I had to turn off my redirection from http to https, then turn off https on my site, then delete the certificate, then re-do `.well-known` validation, then re-issue the "real" certificate, then finally turn back on http to https redirection.  It would have been easier to just have a `--force` option (unless I missed an easy workaround?). I added a PR with some updates to the `README.md` which would hopefully prevent others from running into this, and my experience may have been kind of corner-case-y. Thoughts?

**Comment by ericdorsey** [comment]
> I think my work around would have been to delete the certs from the webfaction admin UI. Then the utility would see them as missing and regenerate them. Do you think that is a reasonable solution?

> Another option, less optimal but potentially zero downtime, would be to change the name of the cert in the config. Then the utility would recognize it as a new cert and issue it.

Definitely reasonable workarounds! I didn't think about, or think to try these as a solution to my problem, but reading them now it seems either would have taken care of my situation nicely. I guess I didn't realize that either one would have triggered the "get me a new cert". I was just getting hung up on the fact that it was just skipping renewal since the stage certificate was just issued. 

Thanks for presenting these workarounds! Will definitely try this if I run into anything similar again (not likely now that I've got the `.well-known` validation and a non-stage valid cert now that will just need renewal). Maybe if someone runs into something similar they can be pointed at this issue, and/or add it as a troubleshooting item in the wiki entries.

**Comment by disadamsdsdnts** [comment]
+1 to the --force option.

I do the same as Eric but I wan't able to delete the cert from WebFaction Admin UI, it doesn't appear 'Delete' button. I change the name, re-create a new cert with another name and copy-paste into the old one. I tried what Eric said, but it doesn't work for me... Thanks for all!

**Comment by will-in-wi** [comment]
@disadamsdsdnts I think the delete button appears on the cert if no websites are using it. The copy-paste option works too!

I certainly need to either add something to the docs or add the flag as suggested. I haven't had time to tackle either yet, and am still considering which one makes more sense. Thanks for the continued feedback!

**Comment by zcaudate** [comment]
another use case is for setting up and talking to the production domain after verifying that staging works.

I get this message if I try running again: 90 days until expiration of <cert>. Skipping...

**Comment by jokkebk** [comment]
Hi. Thanks for superb set of scripts, the 3.0 version is a definite improvement, it will be really easy to set up the automation now with one config.

I ran into this exact same issue, as the documentation is very much set up for this to happen:

1. Run init as instructed
2. Edit the config file as instructed
3. Config comments say you should use the staging first server to ensure everything works
3. Run 'run' and get everything working as instructed
4. Now switch to production setup and 'run' again
5. FAIL

Could it even autodetect from the certificate if it is a staging or a production one? Or not install a staging certificate, as it won't work in production in any case? Just say "everything worked OK, now change config to production"?

Easiest fix is to add to README.md or config docs "When you have tested with staging, you can remove the certificate from WebFaction control panel (make sure no webapps are using it first) and re-run with production config."

**Comment by will-in-wi** [comment]
@jokkebk that wording is a good idea. I just added that to the Readme.

As for autodetecting, I suppose I could do that… The app really has no idea whether an endpoint is staging or production right now, and technically the user could add a completely unrelated endpoint if they wanted. But I _could_ treat the stage/production endpoints as being special… I'd have to see whether there was a reliable way of interrogating a cert to see if it is from stage or prod.

**Comment by fsboehme** [comment]
Another option to force run is to change the domain list. Test with all domains. Rerun test with one domain removed. Add domain back in. Run on production endpoint. That way you don't have to do anything in the webfaction control panel.

**Comment by will-in-wi** [comment]
Just released 3.2.0 with this feature! https://github.com/will-in-wi/letsencrypt-webfaction/pull/150

**Comment by ericdorsey** [comment]
This is fantastic, thank you for adding this!
