### ISSUE TITLE
upgrading the program

### ISSUE THREAD

**Issue by mkahara** [will-in-wi/letsencrypt-webfaction#133]
Hi, trying to upgrade the program but the readme link is 404
https://github.com/will-in-wi/letsencrypt-webfaction/blob/master/docs/README.md#Upgrading

Please assist.

**Comment by ElectricFeet** [comment]
This is correct: 
https://github.com/will-in-wi/letsencrypt-webfaction/blob/master/README.md#upgrading

**Comment by mkahara** [comment]
@ElectricFeet that works, thanks a bunch!
