### ISSUE TITLE
Custom location of the config (letsencrypt_webfaction.toml)

### ISSUE THREAD

**Issue by LotekHeavy** [will-in-wi/letsencrypt-webfaction#136]
I found no option (with the 3.0.1 release) to specific a custom location for the config file (e.g --config ~/etc/letsencrypt_webfaction.toml). Is or will this be supported?

Anyway, thanks for the great tool!

**Comment by will-in-wi** [comment]
It was part of my 3.0 plans, but I needed to cut something to finish it. I didn't know if anyone would find such a feature useful. I'll leave this ticket open until I launch that feature.

**Comment by nootrope** [comment]
I've been using the `--config` parameter with `letsencrypt_webfaction` in my crontab for many months and removing that functionality will break my cert management scheme. :(

**Comment by nootrope** [comment]
@will-in-wi You're absolutely correct. I should RTFM. But your idea of revisiting the --config cli argument is a good one, regardless of whether it supports YAML or just TOML.

**Comment by will-in-wi** [comment]
Version 3.1.0 is released and includes this feature. Thanks!
