### ISSUE TITLE
Does this work for multiple websites?

### ISSUE THREAD

**Issue by jwvanderbeck** [will-in-wi/letsencrypt-webfaction#138]
Hi,

I am unclear on whether or not this can be setup to work for multiple websites with multiple domains.  I *think* it does, but the comments in the configuration file leave me a bit unsure.

For example I have three different independent websites setup in my WF account, and each site has multiple domain entries such as www.example.com, example.com, and blog.example.com.  So Three websites, three domains each, for a total of nine domains across three websites.  Do I just put all nine of those in the `domains` variable, and then list each website in the `public` variable? Or would I need to setup multiple configuration files one for each website?

**Comment by jwvanderbeck** [comment]
*sigh* Ok I really should have finished going through the **whole** config file before opening this issue.  Now I feel like a dolt.

If I understand it, I basically just create one [[certificate]] entry for each website right?

**Comment by ericdorsey** [comment]
@jwvanderbeck 
Not the repo maintainer, but yah, I think you're correct in your second comment there:
```
[[certificate]]
domains = [ "foo.com", "www.foo.com", "blog.foo.com"]

public = "~/webapps/path_of_first_website_in_webfaction"
name = "first_website_cert_name_you_choose"
```
Then another one for:

```
[[certificate]]
domains = [ "bar.com", "www.bar.com", "blog.bar.com"]

public = "~/webapps/path_of_second_website_in_webfaction"
name = "second_website_cert_name_you_choose"
```

**Comment by will-in-wi** [comment]
You have flexibility to do it in a number of ways. Each `[[certificate]]` section represents one certificate with one or more domains (a SAN certificate).

One common way to organize things is to issue one certificate per website. In this case, you'd likely have one or more entries in the `domains` key and only one entry in the `public` key. This would look like @ericdorsey's splendid example in the previous comment.

Another way to organize things would be to issue one certificate to cover a number of different websites. In this case, you'd have several `public` values. This would like as follows, taking the previous example and modifying it:

```toml
[[certificate]]
domains = [ "foo.com", "www.foo.com", "blog.foo.com", "bar.com", "www.bar.com", "blog.bar.com" ]

public = [
  "~/webapps/path_of_first_website_in_webfaction",
  "~/webapps/path_of_second_website_in_webfaction"
]
  
name = "combined_cert_name"
```

The main reason I've seen to use one over the other involves the ["Certificates per Registered Domain" limit](https://letsencrypt.org/docs/rate-limits/) of 20 per week. In the above examples, it is using `foo.com` and `bar.com` which are two "registered domains". But if both examples involved different subdomains of `foo.com`, you might start running into the limit if you constantly issued certs for `foo.com` subdomains. Then it would be recommended to start combining them into the same certificate.

Beyond that use case, it's mostly a matter of personal preference. My practice is to group the domains logically. For example if I have one website running `www.foo.com` and `foo.com` and another website running `blog.foo.com`, I would probably combine these, assuming both websites were closely related. If I had two different websites running `www.foo.com` and `mypersonalfilestorage.foo.com`, I might try to keep these as different certificates.

Does this make sense?
