### ISSUE TITLE
v3 --version no longer works

### ISSUE THREAD

**Issue by abunur** [will-in-wi/letsencrypt-webfaction#139]
after upgrading from v 2.2.2 to v 3.0.1, the command `letsencrypt_webfaction --version` no longer works.  The console says "Unsupported command `--version`. Must be one of init, run"

**Comment by will-in-wi** [comment]
Good catch! I'll get that fixed.

**Comment by will-in-wi** [comment]
The fix is in master and will be released with the next version.

**Comment by will-in-wi** [comment]
Version 3.1.0 is released and includes this fix. Thanks!
