### ISSUE TITLE
TOML template's `name` key could use further clarification

### ISSUE THREAD

**Issue by nootrope** [will-in-wi/letsencrypt-webfaction#142]
One (aesthetic) gotcha for me was that the first cert I generated was listed in the Webfaction admin UI as `mycertname1` because the comment above the `name` key says, 

> The name of the cert...[w]ill default to the cert common name with the dots replaced by underscores.

I does not default to the "cert common name." It defaults to the value of key `name`.

In the end, it was not a huge deal as the staging cert got the `mycertname1` label at which point I caught on, so I was able to name the production cert more meaningfully. 

I will submit a PR (see #143) with a suggested rewrite of the comment. If I'm misunderstanding what you wrote in the template comment, meaning that it is clear enough, apologies! Sincere thanks for a virtually flawless tool.

**Comment by will-in-wi** [comment]
There might be some confusion arising from how I have the default config file set up. If you comment out or delete the `name` key, it _should_ "default to the cert common name with the dots replaced by underscores". If you have the `name` key set (as it is in the default config file), then it doesn't hit the default fallback.

Does this make sense and work as I've described? The language as currently presented is certainly confusing and needs improvement, but I'd like to make sure that 1) there isn't a bug and 2) we are on the same page as to what is supposed to happen.

Thanks!

**Comment by nootrope** [comment]
What I expected with the current language was that leaving the `name` key as-is on the template as I found it from a clean install would nevertheless result in the cert being named the cert common name with dots replaced by underscores.

**Comment by will-in-wi** [comment]
That makes sense… I'm debating how to handle this. The simplest way would be to comment out the `name` key in the default template, triggering the fallback code and forcing the user to manually uncomment it if they want to define a name.

The alternative way would to more explicitly say in the comment that you need to delete or comment out the `name` key in order to see the default behavior. This seems like sub-par UX…

I'd previously thought that I'd want to encourage the user to set a name manually, but I'm now thinking that I don't really care and clarity should win out…

**Comment by nootrope** [comment]
I think that leaving it as-is but with a slightly modified comment would suffice if you distribute the template with `name` commented out.

**Comment by will-in-wi** [comment]
What do you think of https://github.com/will-in-wi/letsencrypt-webfaction/pull/144 ?

**Comment by nootrope** [comment]
That works for me and would have avoided me creating this issue. Thank you!

**Comment by will-in-wi** [comment]
It'll be fixed in the next released version. Thanks for pointing out this issue and helping clarify the UX problem.
