### ISSUE TITLE
 `parse_error': Escape sequence \m is reserved (TomlRB::ParseError)

### ISSUE THREAD

**Issue by commentatorboy** [will-in-wi/letsencrypt-webfaction#145]
In version 3.0.1, when I ran letsencrypt_webfaction run I came upon the following error. 

> ~/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.1/lib/toml-rb/string.rb:38:in `parse_error': Escape sequence \m is reserved (TomlRB::ParseError)

I searched for the `\m` and I noticed it was in the password.
When I changed it, it worked...
So... is it possible to escape that or ?

**Comment by will-in-wi** [comment]
It looks like from the [TOML docs](https://github.com/toml-lang/toml#user-content-string) that you can wrap the password in single quotes. Could you try this?

**Comment by commentatorboy** [comment]
It kind of works.
But now it says the password or username is wrong.
Another queston (sorry for going offtopic).
Is the password the ssh or the admin panel one?

**Comment by will-in-wi** [comment]
No inconvenience, I'm glad you got it working!
