### ISSUE TITLE
Error with sendmail and gmail account_email

### ISSUE THREAD

**Issue by bostondv** [will-in-wi/letsencrypt-webfaction#15]
Hey,

When generating certifications and sending mail to webfaction, sendmail is failing on a particular account that is using a gmail.com address as their account_email.

Running a command like this:

```
$ letsencrypt_webfaction --account_email myemailname@gmail.com --admin_notification_email admin@customdomain.com --domains mydomain.com,www.mydomain.com --public ~/webapps/mydomain/current/web/
sendmail: recipient address support@webfaction.com not accepted by the server
sendmail: server message: 554 5.7.1 < myemailname@gmail.com>: Sender address rejected: Please use Gmail's SMTP servers
sendmail: could not send mail (account default from dummy)
```

I've had no problem using the same basic command on another webfaction account that doesn't use a gmail address as its account_email. Any idea for a workaround other than changing the account email?

Cent OS: centos-release-6-7.el6.centos.12.3.x86_64

**Comment by bostondv** [comment]
Btw, it also works fine on the same webfaction account and just using a different non-gmail account email.

**Comment by will-in-wi** [comment]
Gmail probably has extra restrictions to avoid spam… I think the fix will be to expose configuration for Pony to allow SMTP configuration.

**Comment by will-in-wi** [comment]
I added the ability to do custom config for Gmail in the pony_email_configuration branch. @bostondv, are you able to test the branch? Alternately, I can push an alpha release or something.

**Comment by will-in-wi** [comment]
In testing it myself, it looks like Gmail is now making it difficult to use their smtp servers without OAuth 2.0… It looks like you can turn on insecure logins, or use 2FA and application passwords.

**Comment by will-in-wi** [comment]
Ah, figured it out… Updates coming…

**Comment by will-in-wi** [comment]
Draft notes here: https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Gmail-Configuration

**Comment by will-in-wi** [comment]
Actually after testing, I've pushed version 1.1.0 with some fixes. It should be possible to get Gmail to work now.

Please test! Thanks!

**Comment by bostondv** [comment]
Awesome! Tested using a gmail account with 2FA and an app password. All went well.

**Comment by will-in-wi** [comment]
Splendid. Closing this. Thanks for the report and the test!
