### ISSUE TITLE
Stuck trying to test for certificate using staging server

### ISSUE THREAD

**Issue by stefhone** [will-in-wi/letsencrypt-webfaction#151]
Hi there

Can someone help me please?

I am trying to work my way through the readme - https://github.com/will-in-wi/letsencrypt-webfaction/blob/master/README.md - but stuck at the step testing for certificate using staging server

I have configured _nano ~/letsencrypt_webfaction.toml_, as best I can with some assistance from WebFaction support to get it to this stage. When I try _letsencrypt_webfaction run_ I am presented with the following error....
```
/home/xxxxxx/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.2/lib/toml-rb/keyvalue.rb:13:in `assign': Key "public" is defined more than once (TomlRB::ValueOverwriteError)
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.2/lib/toml-rb/parser.rb:33:in `visit_keyvalue'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.2/lib/toml-rb/keyvalue.rb:32:in `accept_visitor'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.2/lib/toml-rb/parser.rb:13:in `block in initialize'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.2/lib/toml-rb/parser.rb:13:in `each'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.2/lib/toml-rb/parser.rb:13:in `initialize'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.2/lib/toml-rb.rb:46:in `new'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.2/lib/toml-rb.rb:46:in `parse'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.2.0/lib/letsencrypt_webfaction/options.rb:19:in `from_toml'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.2.0/lib/letsencrypt_webfaction/application/run.rb:21:in `initialize'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.2.0/lib/letsencrypt_webfaction/application.rb:30:in `new'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.2.0/lib/letsencrypt_webfaction/application.rb:30:in `new'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.2.0/exe/letsencrypt_webfaction:7:in `<top (required)>'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/xxxxxx/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```
I don't know what the message of a successful test would look like, i'm guessing not like the above message I got?

I can share parts of what i have in my config to help, anyone able to take a look please?

Many thanks

Stef Hone

**Comment by will-in-wi** [comment]
Could you post an anonymized version of your config?

**Comment by stefhone** [comment]
Hi William

This is how my config looks, anonymised with use of xxxx
If the formatting is hard to read I can take a screenshot of the view terminal instead for you.

`# Your Webfaction username and password
username = "xxxx"
password = "xxxx"

# The email address which will be used to register with Let's Encrypt.
letsencrypt_account_email = "xxxx"

# The ACME endpoint. Use the staging server until you get everything working.
# Then switch to the production endpoint. You may want to run with the --force
# command after switching to reissue all certificates.
endpoint = "https://acme-staging.api.letsencrypt.org/" # Staging
#endpoint = "https://acme-v01.api.letsencrypt.org/" # Production

# The URL to the WebFaction API. You should not change this under normal
# circumstances.
#api_url = "https://api.webfaction.com/"

# The hostname of the server you are on. Should be autodetected and not need to
# be changed.
#servername = "web123"

[[certificate]]
# The list of domains for which the cert should be issued. The first will be
# the common name.
domains = [ "dev.lxxxx.com", "lxxxx.com", "www.lxxxx.com" ]
public = [ "~/webapps/lxxx", "~/webapps/l2xxx" ]
name = "lxxxx1"

[[certificate]]
domains = [ "mxxxx.com", "www.mxxxx.com" ]
public = "~/webapps/mxxx"
name = "mxxxx1"

[[certificate]]
domains = [ "wxxxx.co.uk", "www.wxxxx.co.uk" ]
public = "~/webapps/wxxxx"
name = "wxxxx1"

[[certificate]]
domains = [ "ixxxx.co.uk", "www.ixxxx.co.uk" ]
public = "~/webapps/ixxxx"
name = "ixxxx1"

[[certificate]]
domains = [ "gxxxx.co.uk", "www.gxxxx.co.uk" ]
public = "~/webapps/gxxxx"
name = "gxxxx1"

# Right now, only http01 is available. This is the default.
#method = "http01"

# The path to the root of your website. Can be an array as in the second example.
public = "~/webapps/myapp/public_html"
# public = [
#   "~/webapps/myapp/public_html",
#   "~/webapps/myapp/public_html1",
# ]

# The name of your cert in the WebFaction admin interface. Will default to
# the cert common name with the dots replaced by underscores. (Optional)
# NOTE: If you change this and do not also rename it in the webfaction admin,
#	a new certificate will be issued.
#name = "mycertname1"

# The size of the private key. 4096 is the default. You can use 2048.
#key_size = 4096


# A second certificate. All the same keys as above. You should create a
# new [[certificate]] entry for every certificate you want issued. This is a
# simplistic example.
#[[certificate]]
#domains = [
#  "test2.example.com",
#  "test3.example.com",
#]
#public = "~/webapps/myapp/public_html"
#name = "mycertname1"
`

Many Thanks

Stef Hone

**Comment by will-in-wi** [comment]
I think the issue is the uncommented `public` entry towards the bottom of the file, line 53 in the example.

```toml
# The path to the root of your website. Can be an array as in the second example.
public = "~/webapps/myapp/public_html" # <<<< This needs to be commented out.
# public = [
#   "~/webapps/myapp/public_html",
#   "~/webapps/myapp/public_html1",
# ]
```

**Comment by will-in-wi** [comment]
More specifically, TOML doesn't allow duplicate keys. Each `[[certificate]]` section starts a new certificate and allows a new set of keys within that certificate.

The last certificate entry begins and has a `public` entry two lines later. Then again on line 53. That's what the parser is complaining about.

**Comment by stefhone** [comment]
That did the trick. Issuing certificates now. Many thanks for your help!
