### ISSUE TITLE
Upgrading section of documentation in error or outdated?

### ISSUE THREAD

**Issue by jwvanderbeck** [will-in-wi/letsencrypt-webfaction#155]
The instructions for checking the version number seem to be in error or outdated, as even copy pasted from the docs it does not work.

> You can find the current version by running letsencrypt_webfaction --version

```
[jwvanderbeck@web556 ~]$ letsencrypt_webfaction --version
Unsupported command `--version`. Must be one of init, run
```

**Comment by will-in-wi** [comment]
Is this happening in the latest version? I thought I fixed that… https://github.com/will-in-wi/letsencrypt-webfaction/issues/146

**Comment by jwvanderbeck** [comment]
Well the documentation says that in older versions it would just return a "unknown" version, not an error.  So honestly I didn't even think to just update and then try again, as I was mainky trying to just see how out of date I was before risking an update.

I will update and then try it.

**Comment by will-in-wi** [comment]
Yeah, I introduced `--version` a long time ago, and then forgot it in `v3.0.0`. I then fixed that later. 🤦‍♂️

**Comment by jwvanderbeck** [comment]
Ok yes works in newest version.  Sorry about that.  I didn't want to just blindly update so I guess I just had the exact wrong version for this lol.

**Comment by will-in-wi** [comment]
No problem at all! I'm sorry about the gap. I will note that in the docs so that hopefully no one else is surprised. Thanks for noting it here!

**Comment by will-in-wi** [comment]
I added a note here: https://github.com/will-in-wi/letsencrypt-webfaction/commit/d753b8e8414474b2e704555a3d4b48e06a3126c6
