### ISSUE TITLE
Unsupported command `--config`. Must be one of init, run, --version

### ISSUE THREAD

**Issue by bhattisatish** [will-in-wi/letsencrypt-webfaction#158]
Upgraded to 3.2.0 and realise that the upgrade has dropped the config option! How do I pass the config.yaml file to letsencrypt_webfaction? 
In my current workflow I have mutlitple domains with their own directories and configurations. 

The command gives me the following error when I pass the `--config` flag. 

       Unsupported command `--config`. Must be one of init, run, --version

The command I run is as following:

        PATH=$PATH:$GEM_HOME/bin:/usr/local/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction --config $HOME/.letsencrypt_webfaction/mysite.yml

**Comment by bhattisatish** [comment]
I just realised that things have moved. After reading the upgrade guide, which I did post upgrade process :), that now you have one toml file for the whole thing. Need to understand the new configuration before proceeding further. 
Closing this issue as it's not relevant.

**Comment by will-in-wi** [comment]
I'm glad you got that figured out! You may also want to look into WebFaction's new first-party support: https://blog.webfaction.com/2018/09/issue-lets-encrypt-ssl-certificates-with-the-control-panel/
