### ISSUE TITLE
WebFaction now formally supports Let's Encrypt

### ISSUE THREAD

**Issue by danielbachhuber** [will-in-wi/letsencrypt-webfaction#159]
https://blog.webfaction.com/2018/09/issue-lets-encrypt-ssl-certificates-with-the-control-panel/

**Comment by will-in-wi** [comment]
Yup! Woohoo!

I just switched most of my sites over to their support and it works great. So much easier for users than I was ever able to provide.

I added a note to the readme detailing the status of this project in that light.
