### ISSUE TITLE
Complications on Web1XX instances

### ISSUE THREAD

**Issue by ubershmekel** [will-in-wi/letsencrypt-webfaction#16]
/home/myuser/.letsencrypt_webfaction/gems/gems/json-jwt-1.5.2/lib/json/jwk/jwkizable.rb:69:in `<top (required)>': uninitialized constant OpenSSL::PKey::EC (NameError)
        from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/json-jwt-1.5.2/lib/json/jwt.rb:102:in `<top (required)>'
        from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-0.3.1/lib/acme-client.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-0.3.1/lib/acme/client.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/lib/letsencrypt_webfaction/application.rb:2:in `<top (required)>'
        from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/exe/letsencrypt_webfaction:3:in `<top (required)>'
        from /home/myuser/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
        from /home/myuser/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'

**Comment by ubershmekel** [comment]
$ ruby --version
ruby 1.8.7 (2008-08-11 patchlevel 72) [i686-linux]

**Comment by ubershmekel** [comment]
Just found https://github.com/will-in-wi/letsencrypt-webfaction/issues/10 and I'll try the instructions there.

**Comment by ubershmekel** [comment]
```
[xx@web1xx build]$ wget https://www.openssl.org/source/openssl-1.0.2g.tar.gz
--2016-05-10 04:44:05--  https://www.openssl.org/source/openssl-1.0.2g.tar.gz
Resolving www.openssl.org... 194.97.150.234, 2001:608:c00:180::1:ea
Connecting to www.openssl.org|194.97.150.234|:443... connected.
Unable to establish SSL connection.
```
I've downloaded the file locally and used filezilla to sftp it over to the webfaction instance.

**Comment by ubershmekel** [comment]
Everything went well until I got to this step

    PKG_CONFIG_PATH="$HOME/opt/lib/pkgconfig/" RUBY_CONFIGURE_OPTS="--with-openssl --with-opt-dir=$HOME/opt --with-openssl-dir=$HOME/opt" rbenv install 2.2.4

Which brought me this error:

    -bash: rbenv: command not found

**Comment by ubershmekel** [comment]
Installed rbenv with this bash file: https://gist.githubusercontent.com/limeyd/5302716/raw/1bdfe829eb59f1f7786ae63c000ca7074b80f9bc/install_rbenv.sh

    # Get rbenv
    git clone git://github.com/sstephenson/rbenv.git ~/.rbenv

    # Add rbenv to shell
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile

    # reload shell
    exec $SHELL -l

    # Get Ruby-build
    git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

    # setup local $TMPDIR for ruby-build as webfaction /tmp is noexec
    mkdir $HOME/tmp
    echo 'export TMPDIR="$HOME/tmp"' >> ~/.bash_profile

    # install ruby and activate
    rbenv install 1.9.3-p392
    rbenv global 1.9.3-p392

    # install bundler
    gem install bundler

    #update rbenv shims
    rbenv rehash

**Comment by ubershmekel** [comment]
I was able to get the cacert.pm also through filezilla, but then I got this error:

    gems/letsencrypt_webfaction-1.1.0/lib/letsencrypt_webfaction/domain_validator.rb:22:in `validate!': Failed to verify statuses in 10 seconds. (RuntimeError)

I'm a bit tired now. May try again some other day.

**Comment by will-in-wi** [comment]
Sounds like you are really close! Sorry about the web1xx servers, they are tricky to get working.

The last error message you encountered means that everything seems to be working, but LetsEncrypt cannot get to the files you've set up on the server.

https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Troubleshooting

You may want to take a look at the notes for specific servers: https://github.com/will-in-wi/letsencrypt-webfaction/wiki

Please comment back if you have any further issues! I'm happy to try and help resolve them.

**Comment by will-in-wi** [comment]
@ubershmekel: Any success?

**Comment by ubershmekel** [comment]
Thank you so much for this help! The previous road bump was that my .htaccess was preventing access to any folder that starts with a "." to prevent access to the `.git` folder.

We've found yet another bump for good measure

    [xx@web1xx tmp]$ SSL_CERT_FILE=~/build/cacert.pem letsencrypt_webfaction --account_email xx@gmail.com --domains xx.com,www.xx.com --public ~/webapps/xx/
    sendmail: recipient address support@webfaction.com not accepted by the server
    sendmail: server message: 554 5.7.1 <xx@gmail.com>: Sender address rejected: Please use Gmail's SMTP servers
    sendmail: could not send mail (account default from dummy)
    sendmail: recipient address xx@gmail.com not accepted by the server
    sendmail: server message: 554 5.7.1 <xx@gmail.com>: Sender address rejected: Please use Gmail's SMTP servers
    sendmail: could not send mail (account default from dummy)

Which according to this: https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Troubleshooting#sendmail-authentication-issues

I should contact webfaction support.

**Comment by ubershmekel** [comment]
Actually - `echo "Subject: Test Email" | sendmail xx@gmail.com` did work. So this may be a bug with the script?

**Comment by will-in-wi** [comment]
Gmail… https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Gmail-Configuration

https://github.com/will-in-wi/letsencrypt-webfaction/issues/15

Try upgrading to the latest release (if you haven't already) and try the instructions.

The issue is that for webfaction support to know who the email is coming from, the FROM address has to be yours. However, Gmail has some extra security that makes that tricky.

**Comment by ubershmekel** [comment]
Seems to be what I have is letsencrypt_webfaction-1.1.0 which is the latest. I've replaced the gmail address with my `postmaster@xx.com`. Seems to have succeeded in the command line, I've received an email. Let's see if webfaction follows through. Thank you again!

**Comment by will-in-wi** [comment]
My pleasure, glad to hear that this is useful to someone.

**Comment by ubershmekel** [comment]
The ticket worked and the cert was updated. Cheers and thanks.

**Comment by will-in-wi** [comment]
Wonderful!
