### ISSUE TITLE
Cert renewal process failing due to failed redirection

### ISSUE THREAD

**Issue by dlowhorn** [will-in-wi/letsencrypt-webfaction#161]
Has anyone encountered a problem with renewals? My renewal is failing with an error in the log that the attempt to load the .well-known/acme-challenge test file is failing with a 404 error. My full setup follows the norm for SSL redirection.  I have my primary application which is served only by HTTPS, then I have another application (named ssl_redirect) in my WF account that only serves HTTP and has the following .htaccess:

RewriteEngine On
RewriteCond %{HTTP:X-Forwarded-SSL} !on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

This all works great, except for the renewal process. If I manually attempt to access one of the files in the .well-known/acme-challenge subdirectory using HTTPS then the browser finds it just fine, but if I switch to the HTTP protocol, the protocol redirection by my ssl_redirect fails. It just keeps returning 404.

I'm trying to figure this out before my cert expires, so any help would be greatly appreciated.

**Comment by eliot-akira** [comment]
I've been struggling to solve the same issue this afternoon. I have a similar setup, with a single "redirect" application that points from HTTP -> HTTPS sites.

For some reason, the HTTP request to the challenge file is not getting redirected to the HTTPS site, only returning 404 not found.

It seems to be bypassing the `.htaccess` file, and I'm starting to think that maybe WebFaction is handling the route `.well-known/acme-challenge` differently.

Hopefully we can figure out a solution - I'll keep exploring to see what can be done.

**Comment by eliot-akira** [comment]
Aha, I see, it was an issue caused by the "nginx config in place for lets encrypt". That makes sense why it was ignoring the .htaccess. Bit of a pain to do this step for all sites, but I suppose it's only necessary once per site.

Thank you very much for the info.

**Comment by vegemite4me** [comment]
I had this problem, but did not understand what you meant by "a new symbolic link application". I ended up following the [instructions here](https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Exception-RewriteCond-in-.htaccess-to-Allow-Cert-Validation) and the renewal now works. The rewrite section of my .htaccess now looks like this:

```
RewriteEngine On
RewriteCond %{REQUEST_URI} !\.well-known/acme-challenge
RewriteCond %{HTTP:X-Forwarded-SSL} !on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

```
