### ISSUE TITLE
Update to ACMEv2 how?

### ISSUE THREAD

**Issue by fbenji** [will-in-wi/letsencrypt-webfaction#165]
Hi there

Just got a couple of times a warning from letsencrypt that: 
Beginning June 1, 2020, we will stop allowing new domains to validate using
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
then, or certificate issuance will fail. For most people, simply upgrading to
the latest version of your existing client will suffice. You can view the
client list at: https://letsencrypt.org/docs/client-options/

But how to do this without having root rights on webfaction?

https://github.com/unixcharles/acme-client

Any Idea?

Thanks in advance!

**Comment by will-in-wi** [comment]
Are you using this utility to set up your certificates, or WebFaction's native certificate issuance via the control panel?

**Comment by fbenji** [comment]
For some of my Domains I use the WebFaction's Let's Encrypt Option. That works fine for those "only-one-name-Domains". But I do have some other multiple Domains which point to one webside or some have subdomains and need a "shared or custom Certificate". For those I use the letsencrypt-webfaction tool.

**Comment by Nicscott01** [comment]
I use acme.sh to do multiple domains. Learned about this from the recommendation of Webfaction help: [https://github.com/acmesh-official/acme.sh](https://github.com/acmesh-official/acme.sh)

**Comment by will-in-wi** [comment]
I'm going to close this as a dup of https://github.com/will-in-wi/letsencrypt-webfaction/issues/106

I'll take a whack at a port tonight. I've entirely migrated off of this tool myself, and am migrating off of WebFaction for most things. But it seems like a bunch of people are still using it! Which is wonderful, and I'm grateful.

**Comment by will-in-wi** [comment]
I've just pushed version 4.0.0 which supports ACMEv2. This requires changing from endpoint to directory in your config file, which is detailed in the upgrading docs. Please let me know if you encounter any issues!
