### ISSUE TITLE
Moving domain to a new host

### ISSUE THREAD

**Issue by wkbaran** [will-in-wi/letsencrypt-webfaction#17]
I've moved my domain to a new host and I'm not sure how to move the ssl cert.

I had the tree under git and the .well_known directory came over under the public directory of a node app but it's not working yet. Should this directory be available via http?

I've tried reinstalling with letsencrypt_webfaction but I'm getting the error:

    letsencrypt_webfaction --account_email foo@billbaran.us --domains idahobot.billbaran.us --public ~/webapps/idahobot/idahobot/public
    /home/foo/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/lib/letsencrypt_webfaction/domain_validator.rb:22:in `validate!': Failed to verify statuses in 10 seconds. (RuntimeError)
            from /home/foo/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/lib/letsencrypt_webfaction/application.rb:24:in `run!'
            from /home/foo/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/exe/letsencrypt_webfaction:5:in `<top (required)>'
            from /home/foo/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
            from /home/foo/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'

**Comment by will-in-wi** [comment]
I believe that LetsEncrypt will try to access the confirmation page via http, but follow any redirect if needed. So, you need to have http redirect to https for this to work.

Let me know if that helps!

**Comment by wkbaran** [comment]
It looks like there may have been some settings lag and the validation error wasn't too important because it is working now.

**Comment by will-in-wi** [comment]
Glad to hear it! It's good to hear that this utility is proving useful for you.
