### ISSUE TITLE
Alternative to rbenv

### ISSUE THREAD

**Issue by bostondv** [will-in-wi/letsencrypt-webfaction#2]
Hey!

I tried a setup using Webfaction's built-in Ruby 2.2 and everything seemed to work fine and saved some time :)

This is what I did:

1. Added following to `~/.bashrc` to set default ruby version (since Webfaction defaults to 1.8 or 2.0)

    ```bash
    export GEM_HOME=$HOME/gems
    export RUBYLIB=$GEM_HOME/lib
    export PATH=$PATH:$GEM_HOME/bin
    alias ruby=ruby2.2
    alias gem=gem2.2
    ```

2. Run `source ~/.bashrc`

3. Run `gem install letsencrypt_webfaction`

4. Run `letsencrypt_webfaction` command as normal. For cron usage, I prepended the command with `source $HOME/.bashrc;` to make it read the `.bashrc` config.

**Comment by will-in-wi** [comment]
Thanks! I'll test it out and add instructions to the Readme. I might approach it by including the bashrc in the script itself and writing a shell wrapper…

**Comment by will-in-wi** [comment]
@bostondv: Could you take a look at https://github.com/will-in-wi/letsencrypt-webfaction/pull/6 and see if it makes sense to you?

Thanks!

**Comment by will-in-wi** [comment]
Added instructions to Readme. If this has issues, we'll open a new ticket.
