### ISSUE TITLE
beginner's guide for migrating a WebFaction site to HTTPS

### ISSUE THREAD

**Issue by npdoty** [will-in-wi/letsencrypt-webfaction#21]
I've written up a guide on using this tool for migrating a WebFaction site to HTTPS, including the steps needed for configuration and testing, to help friends who might not be sufficiently expert to follow the README alone. If it's useful, please feel free to link from the README or the wiki docs: http://bcc.npdoty.name/directions-to-migrate-your-WebFaction-site-to-HTTPS
Also, corrections or feedback would be welcome; I'm happy to update it.

Apologies for creating a Github issue for this. I would add this to the wiki, but GitHub doesn't allow forks/pull requests on wiki documentation, alas.

**Comment by will-in-wi** [comment]
Added here: https://github.com/will-in-wi/letsencrypt-webfaction/wiki

Good idea on the affiliate link. I might borrow that and add mine to this project. I hope that isn't too self serving…

Thanks!

**Comment by will-in-wi** [comment]
Incidentally, do you mind if I use some of what you wrote to bulk up/clarify the readme? I'll make sure to reference you in the commit. If you want to, you can fork the project and help clarify the readme.

**Comment by npdoty** [comment]
Yeah, please use it in whatever way is useful to improve documentation. I'm not sure everyone will want a README at the level of detail I used (many people reading through github readme's are relative experts), but where it can help, great. I'm probably not going to fork/pull-request the readme in any extensive way at the moment.

I think it's fine to add your affiliate link somewhere in the docs. I wouldn't expect to get a lot of money that way (I'm certainly not), but if it's clear, I think that's a totally appropriate way to receive a benefit from those who use these docs and decide to do business with WebFaction.

**Comment by will-in-wi** [comment]
Based on https://community.webfaction.com/questions/19988/using-letsencrypt, it sounds like they are actively working on control panel integration for cert installation (woot!), so I'm going to hold off on any major reworking of the docs in case this tool is obsolete (or needs to be rewritten) in a month.
