### ISSUE TITLE
Email not sent to Webfaction support

### ISSUE THREAD

**Issue by sebleclerc** [will-in-wi/letsencrypt-webfaction#23]
First of all, my question should be: how much time does it takes for a support ticket to appear in the ticket list?

Now... I am on web301 server, I have the latest 1.1 release and used this command:

PATH=$PATH:$GEM_HOME/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction --account_email=stuff@domain.com --admin_notification_email=info@beerlinked.com --domains=beerlinked.com,www.beerlinked.com --public=~/webapps/directory/

I have received an email to my admin_notification_email, but nothing on the account email and no ticket created in Webfaction help. I have double checked my account email and it's the one labeled as "emergency, invoice, tickets, all emails". No errors thrown...

Thanks for the help!

**Comment by will-in-wi** [comment]
I've seen it take a couple of hours. I think that the support team has to manually create the ticket based on the email.

**Comment by sebleclerc** [comment]
Oh! I probably just created 3 different tickets for the same thing... I'll wait and see for a bit.

I thought I would receive an email to my account_email the same way I did for my admin_notification_email.

**Comment by sebleclerc** [comment]
You were right. I received an email from Webfaction support that my certificate has been installed. Thanks, what an awesome tool!

**Comment by will-in-wi** [comment]
Wonderful! I'm glad it works for you.
