### ISSUE TITLE
Handling dynamic webapps

### ISSUE THREAD

**Issue by osamak** [will-in-wi/letsencrypt-webfaction#24]
One way I have found practical to handle verification of domains with dynamic webapps that are associated with the root path of the domain (e.g. a Django instance at https://example.com/) was to have a static-only app running at https://example.com/.well-known/.  The verification file required by Let's Encrypt would then be created under that app.

Is there anyway to support this rather than requiring a `public_html` folder?

(I have found this to be a more practical way than the solution proposed in #7)

**Comment by will-in-wi** [comment]
That sounds like a good solution. Before someone adds code for this particular solution, could you try this workaround?

You should be able to create a folder called something like `~/site_validations/mysite` and then inside of there create a symlink called `.well-known` to the `.well-known` folder in `~/webapps/mysite`. Then point the utility at `~/site_validations/mysite` and it should recognize that the `.well-known` folder already exists and just use it.

**Comment by will-in-wi** [comment]
@osamak did this work for you?

**Comment by osamak** [comment]
It did! Thank you very much!  Since both ways provide workarounds, I don't think it's particularly useful to support the workaround I had mentioned. To be closed.

**Comment by will-in-wi** [comment]
Glad to hear it!

**Comment by fsboehme** [comment]
Could you add some more description to these instructions please?

Does the app have to be at https://example.com/.well-known or could it be e.g. https://example.com/.verification?

For the second suggestion, is no extra app required? Why/how does this work? How do you set up that symlink?
