### ISSUE TITLE
Letsencript-webfaction (email problems)

### ISSUE THREAD

**Issue by pathros** [will-in-wi/letsencrypt-webfaction#25]
Now I tried with only one domain as you recommended:

------------------------------------------------------------------------
letsencrypt_webfaction --account_email mymail@yahoo.com --domains domain1.com,www.domain1.com --public ~/webapps/myApp/ --output_dir ~/home/username/certs1/
------------------------------------------------------------------------

But now I get the following error:

---------------------------------------------------------------------
sendmail: recipient address support@webfaction.com not accepted by the server
sendmail: server message: 554 5.7.1 <mymail@yahoo.com>: Sender address rejected: Please use Yahoo's SMTP servers
sendmail: could not send mail (account default from dummy)
sendmail: recipient address mymail@yahoo.com not accepted by the server
sendmail: server message: 554 5.7.1 <mymail@yahoo.com>: Sender address rejected: Please use Yahoo's SMTP servers
sendmail: could not send mail (account default from dummy)

---------------------------------------------------------------------
What went wrong?

**Comment by pathros** [comment]
Ahh, I see. The problem was that I had to type an email with the same domain. Now it is working :P

**Comment by will-in-wi** [comment]
Glad it worked for you!
