### ISSUE TITLE
Little addition to install instructions?

### ISSUE THREAD

**Issue by cguerrave** [will-in-wi/letsencrypt-webfaction#28]
Hi, 

First, thank you very much! your script is really easy to use and it saved me a lot of headache!

The only problem I had is that being newbie in many of these things i couldn't make letsencrypt_webfaction work after following the steps, a couple of search later I found my mistake:

After adding the lines in bash_profile i must execute 

`source $HOME/.bash_profile`

I suppose that is obvious for many users but for people with few knowledge in paths like me this could be useful to have in your instructions, besides that everything worked perfectly!

Thank you again!

**Comment by will-in-wi** [comment]
Thanks for the suggestion! I've made the change.

I'm glad you found this useful!
