### ISSUE TITLE
activesupport requires Ruby version >= 2.2.2.

### ISSUE THREAD

**Issue by s512** [will-in-wi/letsencrypt-webfaction#29]
Hi there,

Firstly, great package - it'll help us out a great deal - thanks!

I'm probably missing something glaringly obvious...but... when running the command to install, I get the following error:

```
$ GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem2.2 install letsencrypt_webfaction
ERROR:  Error installing letsencrypt_webfaction:
        activesupport requires Ruby version >= 2.2.2.

```
Is it possible to upgrade the Ruby version? I've tried Googling, but not been successful... Is there something I'm missing? 

I have access to Ruby 2.2.1, but not 2.2.2 AFAIK:

```
$ ruby2.2 --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```

I'm on CentOS v7.2.1511.

Thank you in advance!
Sam

**Comment by will-in-wi** [comment]
Could you try running `GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem2.2 install activesupport` separately?

**Comment by s512** [comment]
No luck unfortunately:

```
$ GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem2.2 install activesupport
ERROR:  Error installing activesupport:
        activesupport requires Ruby version >= 2.2.2.
```

**Comment by will-in-wi** [comment]
I think it is probably because Rails (and ActiveSupport) 5 just came out which doesn't support older versions of Ruby.

Could you try:

```
GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem2.2 install activesupport -v "< 5.0"
```

**Comment by s512** [comment]
Perfect! That's worked and letsencrypt_webfaction installed too.

Thank you!

**Comment by will-in-wi** [comment]
Glad to hear this worked for you!

**Comment by will-in-wi** [comment]
I've released a new version which forces a working version of activesupport. If you already have this working, you don't need to upgrade. But it should keep anyone else from having this issue.

**Comment by bouzidzakaria17** [comment]
Hi Mr.Will-in-wi
I have the same error and i wrote this < GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem2.2 install activesupport -v "< 5.0" >
but i get  " sh.exe": gem 2.2:command not found ".
What is the solution ?
Hoping get answer as soon as possible .
Thanks

**Comment by will-in-wi** [comment]
You need to use a newer version of the Gem that no longer needs activesupport. For the `gem2.2` not found error, you need to make sure that `PATH=$PATH:$GEM_HOME/bin:/usr/local/bin` is in your path, particularly `/usr/local/bin`.
