### ISSUE TITLE
Automatic renewal?

### ISSUE THREAD

**Issue by bostondv** [will-in-wi/letsencrypt-webfaction#3]
I wasn't sure about this from the readme, but with cron usage is it required to contact webfaction every time a new cert is generated to have them install it?

I'm assuming so since each new cert is placed in a new timestamped directory. If the script we to place a copy of the newest certificate in a `current` directory eg. `~/le_certs/domain.com/current` could contacting Webfaction could be avoided?

Thanks!

**Comment by will-in-wi** [comment]
Yes, WebFaction needs to be contacted every time. They move the certs to a protected location and restart the frontend Nginx, so we have no way of changing the in-use certs. Once they have finished installing the certs, you could delete them from `~/le_certs/domain.com` if you wanted.

Great idea! I wish it could work.

This did remind me of another way of approaching it: https://github.com/will-in-wi/letsencrypt-webfaction/issues/4. Feel free to fill in any information you can find about that approach.

Thanks!

**Comment by bostondv** [comment]
#4 sounds like a good solution to me!
