### ISSUE TITLE
Clarify Gmail case in readme

### ISSUE THREAD

**Issue by will-in-wi** [will-in-wi/letsencrypt-webfaction#33]
Continuation of https://github.com/will-in-wi/letsencrypt-webfaction/issues/32

Clarify that the file needs to be created and that the home directory is a good default place for it.

**Comment by will-in-wi** [comment]
@SNaushadS I clarified the configuration file somewhat in https://github.com/will-in-wi/letsencrypt-webfaction/commit/448b00298e3b8defa466be9fc06473479cdb29d5. Does this help?

**Comment by SNaushadS** [comment]
@will-in-wi this makes sense. posted comments inline.
