### ISSUE TITLE
Failed to verify statuses in 10 seconds

### ISSUE THREAD

**Issue by SNaushadS** [will-in-wi/letsencrypt-webfaction#36]
Trying to create certs for other domains and getting error as following: Request assistance.

```
letsencrypt_webfaction --account_email EMAIL_ID --domains DOMAIN.COM --public ~/webapps/webapp_name/
/home/WF_ACCOUNT/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/lib/letsencrypt_webfaction/domain_validator.rb:22:in `validate!': Failed to verify statuses in 10 seconds. (RuntimeError)
        from /home/WF_ACCOUNT/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/lib/letsencrypt_webfaction/application.rb:24:in `run!'
        from /home/WF_ACCOUNT/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/exe/letsencrypt_webfaction:5:in `<top (required)>'
        from /home/WF_ACCOUNT/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
        from /home/WF_ACCOUNT/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

Tried with other email combinations, experimenting with staging endpoint, changing other domain name, But its the same issue.

Thanks.

**Comment by SNaushadS** [comment]
Updated to version 1.1.4 and the same error continues.

**Comment by will-in-wi** [comment]
That means `~/webapps/webapp_name/` isn't serving `DOMAIN.COM`. Or at least someone hitting `DOMAIN.COM/.well-known/something` can't actually get to it. If you are running Drupal or some other systems, you might have an issue with htaccess.

Some help on htaccess files is here: https://github.com/will-in-wi/letsencrypt-webfaction/wiki#notes-for-specific-setups

Some debugging help is here: https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Troubleshooting#failed-to-verify-statuses-in-10-seconds

**Comment by SNaushadS** [comment]
Hi William,
The setup is wordpress. and i have

I checked, the .well-known folder, it was created however it is not publicly accessible due to .htaccess block.

However, i am not sure how this would impact as i followed the exact same steps earlier on 2 other WordPress installations, without any issue, in those cases also the content of .well-known is not accessible over public url.

**Comment by will-in-wi** [comment]
It shouldn't work at all if the `.well-known` files are unavailable. I'm not sure how the other installations worked.

**Comment by SNaushadS** [comment]
Phew.. Strangely, the command worked for a WordPress domain, even a ticket was created.

All of this when the folder .well-known and sub-folder acme-challenge is behind .htaccess and trying to access it over url gives 403 Forbidden.... Im confused now. But works for the moment.

**Comment by will-in-wi** [comment]
To be clear, are you referring to a literal url of `http://example.com/.well-known` or the actual url of something like `http://example.com/.well-known/acme-challenge/SBlCa_XjKkjsdfhHHK8nhOwCT280-789kY-DOJxyKJDAY4` ?

**Comment by will-in-wi** [comment]
The former would give you a 403 forbidden since you can't do directory listings.

**Comment by ElectricFeet** [comment]
I also got this error when I had changed an https's website status from disabled to enabled in WebFaction's control panel. When you change the status, they give you a warning message saying that it will take a little while to propagate. Could it be this?

**Comment by SNaushadS** [comment]
@will-in-wi, yes, i was referring to the literal URL. I tried accessing the actual url as you described and it is indeed accessible.

Just tried the script with a non-gmail id for another domain and it worked seamlessly.

From my end this can be closed, unless you have some specific questions Or someone else has same issues.

**Comment by will-in-wi** [comment]
@ElectricFeet: I think this is just due to WebFaction's server configuration code taking a while to actually change the servers.

@SNaushadS: I think we'll just call this one closed. I'm glad you got it working!
