### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by ElectricFeet** [will-in-wi/letsencrypt-webfaction#37]
Hi William,
Good news! I've been able to get a few sites working so far :))))))))

Even better news is that I'm writing a How-To for WordPress sites. I wrote it really for myself, as I had several sites to do and a terrible memory. I wrote a lot of it and then realised that Nick Doty's guide covers a lot of the same ground. Mine's more newbie-targeted, explaining what a lot of stuff means (now I've worked it all out for myself).

It could probably go in the Wiki. Are you interested? Shall I attach it here when finished (probably tomorrow)? Or is there a way I can fork the wiki? Layout is markdown; correct?

**Comment by will-in-wi** [comment]
That's wonderful news!!!

I'm fine with a couple of options:

* You can post the tutorial somewhere and I'll link to it
* I can post the tutorial on the wiki

If you think the wiki option works better, write it in markdown and throw it in this ticket and I'll upload it.

Thanks!

**Comment by ElectricFeet** [comment]
Hi William,
Sorry for the delay. It's taking me longer than I thought. Should be ready some time early this week.

However, as I'm writing, I have come across what I think might be a problem:

I have so far generated 3 certificates; two on my own WebFaction account and one that I'm working on with a friend.

In two cases (one on my account; one on my friend's), WebFaction staff have created a folder called `~/certificates` and made what look like copies of relevant files in the `~/le_certs` subfolder.

That is, they seem to have taken `fullchain.pem` and `privkey.pem` from `~/le_certs` and copied them into `~/certificates/[my_sll_website].cert` and `~/certificates/[my_sll_website].key`. 

In the third case they have created no such `~/certificates` folder, so I presume the certificate is installed "in place". (As I'm not sure what is involved in installing the cert, I don't know how to explain it.)

However, for the Cron renewal, will all three cases renew OK, or will 2 of them fail because the cert files have moved? (I'm not even clear if the renewals need intervention from WebFaction Support.) If they will fail, then (a) I need to raise a ticket to get the certs in the right place and (b) you will need to change the email that is generated, to ask them to leave them in the right place in the first place.

Not sure what I should make of the same task being handled differently by support staff...

**Comment by will-in-wi** [comment]
This is mostly an informed guess, but I'm guessing that WF has classes of servers with slightly different procedures for each.

In the `~/certificates` case, the files are set to be owned by root. Thus, you can't modify them. I'm guessing that they have the same setup in a different folder you can't see on your friend's server.

When you run this app, a new cert is dropped into a new folder inside of `~/le_certs`. The WF support team will copy these new files into whatever folder they are using and change the server configuration to use them.

You can delete the certs if you want to as soon as WF support has confirmed installation. They've been copied somewhere else.

Does this make sense/help?

**Comment by ElectricFeet** [comment]
Apols. I just edited the orig comment dues to stupidly not having refreshed my SFTP view :(((

**Comment by ElectricFeet** [comment]
> You can delete the certs if you want to as soon as WF support has confirmed installation. They've been copied somewhere else.

Ah, interesting. Do you recommend this, for tidiness' sake?

**Comment by will-in-wi** [comment]
It's always good to be tidy. But the definition of tidy is subjective, so I will leave it up to you whether having the files cleaned up is better than leaving them in the folder. There is no good objective reason either way.

I personally have just left them. I may clean them up someday.

**Comment by ElectricFeet** [comment]
Thanks!

One final question: does the Cron renewal need WebFaction Support involvement?

**Comment by will-in-wi** [comment]
Yes. The cron job will also send WF support an email so that they can install the new certificate.

**Comment by ElectricFeet** [comment]
Ah OK. So I presume they'll know where to find it as they put it there :))

**Comment by ElectricFeet** [comment]
Hi William, further apologies for the delays. I'm tying myself in knots trying to figure out the best options for redirection: https://community.webfaction.com/questions/20176/redirects-https-and-non-www-how-to-get-both-working-together?

**Comment by will-in-wi** [comment]
Hmm. I'll tell you what I personally do:

I have a WebFaction application (static with htaccess) which I call `ssl_redirect`. For every application that I want to use https, I send the http version to this app.

Inside the app is just an htaccess file containing:

```apache
RewriteEngine On
RewriteCond %{HTTP:X-Forwarded-SSL} !on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```

I'll take care of the www vs. non-www question inside each app itself after it has been redirected to https.

I'm not sure this is the "best" way, but it works well for me.

**Comment by ElectricFeet** [comment]
Well here it is. It was a bit of a marathon, but I've got things working on 4 sites so far, with a couple to go and the instructions seem pretty robust! Let me know what you think!
[https-webfaction.txt](https://github.com/will-in-wi/letsencrypt-webfaction/files/392627/https-webfaction.txt)

**Comment by will-in-wi** [comment]
WOW! This is splendid! I'm going to start reading through it in detail, but would you like this on my official Wiki, or are you going to host it yourself?

**Comment by ElectricFeet** [comment]
The official wiki would be an obvious place and I'm not precious about it -- as long as you give me credit :-)

I think it would be a good idea to link to it in the readme too, as I didn't realise there was a wiki until you pointed it out on another thread. Casual GitHub users don't know these things :-)

Have fun reading :-)

**Comment by will-in-wi** [comment]
I haven't had time to read the whole thing, but I added the wiki page: https://github.com/will-in-wi/letsencrypt-webfaction/wiki/wordpress-guide

Wiki editing access is now open, so feel free to update the guide. (Or contribute more docs!)

I'll make a note to myself to add a link to the wiki to the readme.

Thanks!

**Comment by ElectricFeet** [comment]
Great!

I got an invitation to the repository in an email, but when I clicked the link, it gives `Sorry, that repository invitation does not exist.` But it all seems to work, so hey-ho.

I deleted the other "wordPress" page in the wiki &mdash; (a) because it's superseded by the wordpress-guide page and (b) because it was wrong :-) 

It said: 

> By default, a WebFaction Wordpress site is installed with its docroot in `~/webapps/[sitename]`. You know this is the case if you see `index.php` in this folder.

> In this case, you would set `--public ~/webapps/[sitename]`.

Which is not actually the case. It's in `~/webapps/[appname]`. 

Promise not to delete anything else.

Closing this, as we seem to be done on this issue. Yay!

**Comment by will-in-wi** [comment]
Sweet! Sorry for the invite email. I was trying to see if I could add a collaborator who could edit the wiki, and the only way to do it gives full access to everything. So I canceled the invite and opened the wiki to everyone.

Thanks for your help!
