### ISSUE TITLE
See if support can be automatically emailed

### ISSUE THREAD

**Issue by will-in-wi** [will-in-wi/letsencrypt-webfaction#4]
I have an idea that I haven't explored, where we make the script email `support@webfaction.com` from your registered account, in order to automatically create the ticket. Hypothetically, this would make it entirely hands-off (for us). However, I haven't verified that emailing them from your email address would actually create the support ticket such that you can see it in the support page.

Tasks:
* Confirm that having cron email support@webfaction.com with `MAILFROM=you@example.com` actually creates a valid ticket.
* Modify the script to accept a direct-to-webfaction message flag.

**Comment by bostondv** [comment]
I like this idea :)

I've sent a test email to support@webfaction.com from my account email address and it successfully created a support ticket.

As someone who manage's a lot of client's certs it'd be nice to be able to specify a CC email address in the email being sent out to webfaction if possible.

**Comment by will-in-wi** [comment]
Note to self: Try Pony with local sendmail.

https://github.com/benprew/pony

**Comment by will-in-wi** [comment]
I've reworked this on master to send an email to support. Feel free to test. I'm going to work on https://github.com/will-in-wi/letsencrypt-webfaction/issues/2 and then push a release.

**Comment by bostondv** [comment]
Hey, just testing out now! Seems to be working and ticket appeared in Webfaction support but have a couple issues:

The `--contact` arg must be the primary contact in the webfaction account? is it possible specify a different email address to receive the notification at so I as the technical contact can get the notification instead of the account holder?

This was the email Webfaction received. Probably should only send them the last part?

> LetsEncrypt Webfaction has generated a new certificate for domain.com and www.domain.com. The certificates have been placed in /home/domain/le_certs/domain.com/20160324162750. WebFaction support has been contacted with the following message:
> 
> Please apply the new certificate in /home/domain/le_certs/domain.com/20160324162750 to domain.com and www.domain.com. Thanks!

Lastly, I ran the command 3 times and each time it generated new certificate and sent a support email to webfaction. Is there any way to make the command exit if a valid certificate with say 1+ months remaining already exists?

**Comment by will-in-wi** [comment]
Hmm good points.

There are a couple of email addresses involved here:

1. Account address from which the email to WF support will come
2. Webfaction support email address (I assume that everyone will use the default here)
3. Personal notification email
4. LetsEncrypt account email

I guess I assumed (wrongly) that nos 1 and 3 would be the same. I will create a config key and command line argument for each of the above, making the names more clear. By default, 2 will be support@webfaction.com, and 1 will be required with 3 and 4 using 1 if not configured distinctly.

How do these sound to you?

1. `--account_email`
2. `--support_email`
3. `--admin_notification_email`
4. `--letsencrypt_account_email`

Does the above make sense?

I thought I had coded it to only send WF the last part. I'll fix that.

Per the last point, I'm not sure how to handle it. My instinct is to just say that when you run the command, it will always get a cert. You as the admin are responsible for not running it too much. With that said, I could see a situation where it refuses to create a cert in the situation you mentioned, but could be overridden with a `--force` param. I'm just not sure whether it is worth the additional complexity. It would be a non-insignificant amount of new code to list existing certs, and parse them to determine domains and age. Is it worth it? I would hope that anyone doing testing with this would use the LE stage server which doesn't have the same rate limits.

Thanks for your input!

**Comment by bostondv** [comment]
Those email changes make sense to me! I'd figure the majority of users wouldn't need 3 and 4, but it's nice to have the option for my use case.

I think it's probably smart to not to introduce more complexity and fair to leave it up to user to test with it reasonably. 

What may have prompted my thinking was that I'm pretty sure I ran the command at least once with `--support_email ""` arg and still got an email notification that said Webfaction has been contacted. It could be a mistype on my end, but may be worth checking if there's a bug?

**Comment by will-in-wi** [comment]
I'll check on the `--support_email ""` issue. I think you are right that it is a bug.

**Comment by will-in-wi** [comment]
Ticket for `--support_email ""`: https://github.com/will-in-wi/letsencrypt-webfaction/issues/8

Ticket for sending email to support without wrapper: https://github.com/will-in-wi/letsencrypt-webfaction/issues/9

**Comment by will-in-wi** [comment]
I think I've got everything fixed here. I'm going to close this and cut a 2.0.0 release (since the way the app is used has changed).

Thanks for the feedback! Please keep filing issues as they arise.

**Comment by will-in-wi** [comment]
Correction, a 1.0.0 release. I forgot that the latest version was 0.0.2.
