### ISSUE TITLE
Cronjob configuration ruby2.2 full path

### ISSUE THREAD

**Issue by osamak** [will-in-wi/letsencrypt-webfaction#44]
It seems that `ruby2.2` resides outside `PATH` when running a cronjob in WebFaction, so it would be safer to change the documentation to advise people to call `ruby2.2` using its full path in the system installation, which is `/usr/local/bin/ruby2.2`.

The cronjob command would be:

`PATH=$PATH:$GEM_HOME/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib /usr/local/bin/ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction --account_email [you@youremail.com] --domains [yourdomain.com,www.yourdomain.com] --public ~/webapps/[yourapp/your_public_html]/`

(I just noticed that my certificates were not being updated due to a failure to execute `ruby2.2`)

**Comment by will-in-wi** [comment]
Huh. Good catch. On my system, the PATH is `/usr/bin:/bin`.

However, $GEM_HOME is defined in the following stanza and doesn't include Ruby…

I'd imagine that the correct PATH would be: `PATH=$PATH:/usr/local/bin`.

I'll add that to the readme. Thanks!

**Comment by osamak** [comment]
Thank you so much!  Keep the amazing tool.
