### ISSUE TITLE
Error 404 when acme challenge in version 1.1.8

### ISSUE THREAD

**Issue by pathros** [will-in-wi/letsencrypt-webfaction#45]
Hello, I had no problems before. But now when applying the letsencrypt_webfaction command, it returned error ... I checked out the version and the result was unknown. According to the docs, I upgraded and now I got the 1.1.8 version. So I ran the command again and now I have this 404 error on acme challenge.

```
Failed to verify statuses.
myDomain.com: Invalid response from http://myDomain.com/.well-known/acme-challenge/1aE...
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
Make sure that you can access http://myDomain.com/.well-known/acme-challenge/1aE...
```

I try that URL on my browser and get the following:
```

Not Found

The requested URL /avsOVY1C4PXoS.....-qLe8wgw7YVJo was not found on this server.
```
Looks like the confirmation chain is not displayed.

Any ideas how to fix it?

**Comment by will-in-wi** [comment]
It looks like the WF team have been running into issues with this: https://github.com/will-in-wi/letsencrypt-webfaction/issues/43

Could you open a ticket with them and report back here?

Thanks!

**Comment by will-in-wi** [comment]
For simplicity's sake, I'm closing this as a "dup" of #43.
