### ISSUE TITLE
Error creating new registration

### ISSUE THREAD

**Issue by pieplu** [will-in-wi/letsencrypt-webfaction#46]
Hi, I try to generate a new certificate.
I updated `letsencrypt_webfaction`, lanch this command:

```sh
letsencrypt_webfaction --account_email my@domains.com --domains my.domains.com --public ~/webapps/path --endpoint https://acme-staging.api.letsencrypt.org/ --support_email "email@email.com"
```
And have this result:
```sh
Failed to verify statuses.
my.domains.com: Invalid response from http://my.domains.com/.well-known/acme-challenge/oCm1uCAzKDX45FlML-PyirQEf30iqYmtuP148_WNUZs: "<!DOCTYPE html>
<!--[if lte IE 8]><html class="ng-csp ie ie8 lte9 lte8" data-placeholder-focus="false" lang="en" ><![endif]-->
<"
Make sure that you can access http://my.domains.com/.well-known/acme-challenge/oCm1uCAzKDX45FlML-PyirQEf30iqYmtuP148_WNUZs
```
I try an other time, and have this:
```sh
/home/me/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client/faraday_middleware.rb:43:in `raise_on_error!': Error creating new registration (Acme::Client::Error)
	from /home/me/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client/faraday_middleware.rb:33:in `on_complete'
	from /home/me/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client/faraday_middleware.rb:18:in `block in call'
	from /home/me/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /home/me/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client/faraday_middleware.rb:18:in `call'
	from /home/me/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/me/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /home/me/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /home/me/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client.rb:45:in `register'
	from /home/me/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.8/lib/letsencrypt_webfaction/application.rb:70:in `register_key!'
	from /home/me/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.8/lib/letsencrypt_webfaction/application.rb:21:in `run!'
	from /home/me/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.8/exe/letsencrypt_webfaction:5:in `<top (required)>'
	from /home/me/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/me/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

For test, I remove the file `.well-known/acme-challenge/oCm1uCAzKDX45FlML-PyirQEf30iqYmtuP148_WNUZs` and have exactly the same error (the second)

I read than my first error is a webfction matter, but the second looks diffrent

**Comment by will-in-wi** [comment]
When you run it now, do you get the second error, or the first?

**Comment by pieplu** [comment]
Now now, the first O_O
(But after removed the file, the second...)

**Comment by pieplu** [comment]
**Edit:** For the first error, it's completly my fault (and the .htaccess of my webapp...)

**Comment by will-in-wi** [comment]
Ah, I'm glad you were able to resolve the first issue. Are you able to consistently reproduce the second issue? I've never seen it before and am inclined to blame a transient LE server error.

Is the htaccess file your own custom one, or is it part of an app like Drupal or Wordpress? I'm trying to catalogue the programs which need htaccess modification.

Thanks!

**Comment by pieplu** [comment]
Not append an other time... I think too!

The webapp is owncloud 8. (owncloud 9 and nextcloud 9 have the line `RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge/.*` ) But 8 not...

**Comment by will-in-wi** [comment]
> Not append an other time... I think too!

Sorry, I'm having trouble parsing that. Are you saying that you were not able to reproduce?

Thanks for letting me know about OwnCloud 8. I'll add a note about that to the wiki.

**Comment by pieplu** [comment]
Sorry for my English ^^.
Yes, I'm not able to reproduce. I think you can close this issue.

Thank you very much for your work and your involvement :)

**Comment by will-in-wi** [comment]
Sounds good! Thank you for reporting.
