### ISSUE TITLE
Lets Encrypt Malformed CSR Advisory

### ISSUE THREAD

**Issue by SNaushadS** [will-in-wi/letsencrypt-webfaction#48]
Hi William,

Have received the following message from Lets Encrypt.

> Based on a certificate request you have submitted over the last three months we believe you are using a version of Certbot (formerly known as the letsencrypt Python client) less than 0.4.1, or a different client and a version of OpenSSL less than 1.0.2. A bug which has been fixed in newer versions of both Certbot and OpenSSL causes requests produced by the buggy software to be rejected by the Let’s Encrypt server.
> 
> Due to the complexities of working around this bug we plan to introduce a hard cut off date for these malformed certificate requests of two months from this notification (November 17th, 2016) after which they will fail.
> 
> If you wish to continue issuing certificates after November 17th you must update your client software.
> 
> In order to fix this issue you must update your servers to use the newest version of Certbot, or if you are using another client, to use the most recent version of OpenSSL. Depending on which operating system you use this may be as simple as upgrading the packages using your system package manager. For more information about upgrading you can refer to this post on the community forum: https://community.letsencrypt.org/t/openssl-bug-information/19591.
> 
> If you are using a client other than Certbot you may also wish to open a support ticket for the client (if one does not already exist) so that the developers can be alerted to the issue and address it. For further information you can link them to this post on the community forum: https://community.letsencrypt.org/t/openssl-bug-information/19591.
> 
> Let's Encrypt Team
> 

Could you please advise on how to approach this ? Do i have to work something on the le-wf gem OR update something else.

Thanks.

**Comment by will-in-wi** [comment]
Do you know what version of Acme::Client you are using? It looks like this was fixed in Acme::Client v0.4.1. https://github.com/unixcharles/acme-client/commit/a73c7e09c5982af249757e07e12e98ec6d2767d8

**Comment by SNaushadS** [comment]
I have just installed le-wf script and do not recall installing Acme separately. How do i check that ?

Also i had updated le-wf plugin once.

**Comment by will-in-wi** [comment]
Could you post the output of one of these commands (depending on your case):

```bash
GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem list --local | grep acme-client
RBENV_ROOT=~/.rbenv RBENV_VERSION=2.3.0 ~/.rbenv/bin/rbenv exec gem list --local | grep acme-client
```

**Comment by SNaushadS** [comment]
Here
acme-client (0.3.6, 0.3.1)

**Comment by will-in-wi** [comment]
Ah! Could you run one of the following?

```bash
# System Ruby
GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem update acme-client
GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem cleanup acme-client

# rbenv
RBENV_ROOT=~/.rbenv RBENV_VERSION=2.3.0 ~/.rbenv/bin/rbenv exec gem update acme-client
RBENV_ROOT=~/.rbenv RBENV_VERSION=2.3.0 ~/.rbenv/bin/rbenv exec gem cleanup acme-client
```

**Comment by will-in-wi** [comment]
After you run that, the output of the previous `gem list --local | grep acme-client` command should be `acme-client (0.4.1)`

**Comment by SNaushadS** [comment]
This is the o/p that i get:
```
Updating installed gems
Updating letsencrypt_webfaction
ERROR:  Error installing letsencrypt_webfaction:
        acme-client requires Ruby version >= 2.1.0.
Nothing to update
```

And when i check for the ruby version installed with _ruby -v_

I Get:
`ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]`

Tried checking how to user Ruby 2.1 at this link [Webfaction Ruby](https://docs.webfaction.com/software/ruby.html), but the command _ruby2.1_ just freezes

My CentOS Version is CentOS 6 and defauly Ruby Version is 1.8.7

Appreciate your help. Thanks.

**Comment by will-in-wi** [comment]
Ah, I messed up the first set of commands. You aren't using rbenv and need `gem2.2` not `gem`.

I've fixed that. Could you try again?

**Comment by SNaushadS** [comment]
Im sorry, but i do not see gem2.2 in the [comment](https://github.com/will-in-wi/letsencrypt-webfaction/issues/48#issuecomment-248886136) could you please help me with the exact command ?

I am used to CLI but the ruby paths are more cryptic to reach... :)

**Comment by will-in-wi** [comment]
```bash
GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem2.2 update letsencrypt_webfaction
GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem2.2 cleanup acme-client
```

**Comment by SNaushadS** [comment]
Got it thx.

When i run the command i get this output.

```
GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib gem list --local | grep acme-client
acme-client (0.4.1, 0.3.6)
```

Hopefully, this should resolve the issue. Closing.

**Comment by sebleclerc** [comment]
@will-in-wi  Got the same issue (was working with AcmeClient 0.3.0) and updating LetsEncrypt-Webfaction did the trick! Thanks!
