### ISSUE TITLE
Cron failed

### ISSUE THREAD

**Issue by ElectricFeet** [will-in-wi/letsencrypt-webfaction#49]
Hmm. I've been following various errors that people have been encountering lately (and also the positive developments on the webfaction side). I haven't really followed well enough to figure out if the errors have been fixed upstream.

I've now gone past crunch-time -- renewal -- and my cron commands clearly didn't work (I'm getting 20-day cert expiry warnings from Let's Encrypt (which is nice of them). 

So my issue is: Is the command in the cron job at fault, or did I bump into some of the errors when my renewals ran on 11 Sept? (I hadn't updated my version of LE-WF since August; but I have now.)

Any chance you could double check that my wiki-wordpress-doc cron command is correct? 

If it's correct, can I assume I can change the cron date to tonight and it will update correctly? Or are there still some upstream errors around in LE-WF?

Thanks!

**Comment by will-in-wi** [comment]
I'm not sure… Do you have error messages? If you try to manually run the commands, do they return errors?

I'm waiting for WF to release the API and docs so that I can update the client. Until then, things are kind of in the air, but should continue to work.

**Comment by ElectricFeet** [comment]
OK, I let the cron run again and I got no email and the cert is still showing as expiring soon.

Triple checking --- I can't see how I failed to spot this yesterday and before! --- I see that my wiki guide is wrong. I'm missing the `:/usr/local/bin` in `PATH=$PATH:$GEM_HOME/bin:/usr/local/bin GEM_HOME=$HOME/.letsencrypt_webfaction...`

Q1: Could you correct the wiki? Sincere apologies to you, and anyone reading this who followed the wiki guide (note to anyone who did: correct your cron once will-in-wi has updated the wiki!)

Q2: Just now, I ran the (correct) command via SSH (adding myself as support, so as not to bug WF if it didn't work) and everything worked fine. I now have to paste the certs in the control panel. Am I correct in thinking that the files in the `~/le_certs/[domain_name]/[timestamp]/` folder and the entries in the webFaction control panel map as follows:

`cert.pem` = "Certificate"
`chain.pem` = "Intermediates/bundle"
`privkey.pem` = "Private key"

Thanks and apologies again for screwing up the wiki.

**Comment by will-in-wi** [comment]
I've made the correction to the wiki. Thanks for pointing that out!

Yes, you have the correct mapping of cert/chain/private key to the new admin UI.

I'm glad you got it working!

**Comment by ElectricFeet** [comment]
Thanks! :)
