### ISSUE TITLE
Example letsencrypt_webfaction() bash function doesn't work for ZSH

### ISSUE THREAD

**Issue by danielbachhuber** [will-in-wi/letsencrypt-webfaction#50]
Tried adding it here: https://github.com/danielbachhuber/dotfiles/commit/ea89fb7e3282f28b9da90fefb4b1cdbd8b73333d

```
web524.webfaction.com ➜  .dotfiles git:(master) ✗ reload!
web524.webfaction.com ➜  .dotfiles git:(master) ✗ letsencrypt_webfaction --account_email wpcli@handbuilt.co --domains github-api.wp-cli.org --public ~/webapps/github_api
zsh: command not found: letsencrypt_webfaction
web524.webfaction.com ➜  .dotfiles git:(master) ✗ bash
bash-4.2$ letsencrypt_webfaction --account_email wpcli@handbuilt.co --domains github-api.wp-cli.org --public ~/webapps/github_api
bash-4.2$ echo $?
0
```

**Comment by will-in-wi** [comment]
I don't personally use ZSH or have any experience in writing functions for it.

I'd welcome a doc fix with a ZSH version of the script.

**Comment by danielbachhuber** [comment]
Sorry, I just realized I didn't finish my message here. Just opening the issue to log it. If I can track down the fix, I'll submit a PR with the doc fix.

Thanks for your great utility!

**Comment by danielbachhuber** [comment]
> I'd welcome a doc fix with a ZSH version of the script.

As it turns out, this function works in a `.zshrc`. Not sure what my issue was before.
