### ISSUE TITLE
".well-known" URL returns 404

### ISSUE THREAD

**Issue by KoreyPeters** [will-in-wi/letsencrypt-webfaction#53]
Hi there. I'm using Django 1.10 and I've created a static app from www.example.com/.well-known to ~/public_html such that if I put a file (say test.html) in ~/public_html and browse to www.example.com/.well-known/test.html it renders properly.

But when I run
$ letsencrypt_webfaction --account_email me@example.com --domains example.com,www.example.com --public /home/username/public_html/

I get 404 errors that it couldn't find www.example.com/.well-known/acme-challenge/some-hash

When I look in ~/public_html, there's nothing in there. Do you have any suggestions?

**Comment by will-in-wi** [comment]
Did you use `ls -a` to see hidden files and folders?

**Comment by KoreyPeters** [comment]
Gah. When I was looking for a fixed I forgot to check for closed issues (which are filtered by default). I'm probably having exactly the same issue everyone else did. I've got a different cert installed which will last me the year. Thanks for your help (and sorry for wasting your time :()
