### ISSUE TITLE
Fails to log in to WebFaction API

### ISSUE THREAD

**Issue by pymarco** [will-in-wi/letsencrypt-webfaction#55]
Thank you for creating the new release!

My certificate is being created, but XMLRPC login fails. I've confirmed I didn't make a typo by logging into WF by copying and pasting from my command. Also, I have used the same credentials by making api calls of my own.

Here's the command and output with sensitive info replaced.

    $ letsencrypt_webfaction --letsencrypt_account_email me@example.com --domains example.com --public ~/webapps/example_http/ --username myuser --password LETMEIN --endpoint https://acme-staging.api.letsencrypt.org/

    /usr/local/lib/ruby22/ruby/2.2.0/xmlrpc/client.rb:271:in `call': LoginError (XMLRPC::FaultException)
    from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/certificate_installer.rb:33:in `session_id'
    from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/certificate_installer.rb:14:in `install!'
    from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:26:in `run!'
    from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/exe/letsencrypt_webfaction:5:in `<top (required)>'
    from /home/myuser/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
    from /home/myuser/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'

**Comment by will-in-wi** [comment]
My first guess is that there might be some special chars in your password that Bash doesn't like. Could you try quoting it, or using the config file by creating `something.yml` in your home dir containing

```yaml
username: "myuser"
password: "LETMEIN"
```

and then adding `--config something.yml` to the command?

Thanks!

**Comment by pymarco** [comment]
I believe the issue was special characters in my password. I created a yaml config file as instructed and it work without error. 

Thanks!! You are awesome!!!

**Comment by will-in-wi** [comment]
Sweet! I'm glad it works for you.

**Comment by desduvauchelle** [comment]
I'm having the exact same error. I also created a `config.yml` with just username and password, and still no luck. 

I even logged in via SSH by copy and pasting my username and password to make sure they are correct (and they are). 

I tried running it from the root user directory (~) and also from the directory I'm trying to use (~/webapps/my-app/) with no luck. 

Any ideas?

**Comment by desduvauchelle** [comment]
Hello. 
I'm having the exact same issue. 

1. I also copy/pasted my username/pwd to make sure it wasn't a typo by logging in via SSH (I just put my username/password in the config file).
2. I created a config.yml file as recommended. Still no luck

Any other ideas?

**Comment by will-in-wi** [comment]
@desduvauchelle, I'd confirm that you have the right username/password. Your SSH password can sometimes be different.

Failing that, could you post the command you are running, and the error message?
