### ISSUE TITLE
letsencrypt-webfaction can't find/open conf file

### ISSUE THREAD

**Issue by ndkv** [will-in-wi/letsencrypt-webfaction#58]
This is borderline banal but I can't get `letsencrypt-webfaction` to find/read my conf file located at `~/le_config/config.yml`. The command 

    letsencrypt_webfaction --config [~/le_config/config.yml] --public ~/webapps/public_folder

Returns the following error:

    /usr/local/lib/ruby22/ruby/2.2.0/psych.rb:464:in `initialize': No such file or directory @ rb_sysopen - [~/le_config/config.yml] (Errno::ENOENT)

Any ideas how to fix this?

**Comment by panzerdp** [comment]
You probably should remove the square brackets `[ ]` from the path:

    letsencrypt_webfaction --config ~/le_config/config.yml --public ~/webapps/public_folder

**Comment by will-in-wi** [comment]
@ndkv: I concur with @panzerdp, I think this is the issue.

I'll close this issue presuming that it will work for you. If not, please comment back and I'll reopen the ticket.

Thanks!

**Comment by ndkv** [comment]
Yes, that did it. The `[]` in the example threw me off, though. I'm used to reading `[]` to mean optional parameters while you're using them to indicate user-specific parameters. This is fine, however, the very first example doesn't use square brackets

    $ letsencrypt_webfaction --letsencrypt_account_email you@youremail.com --domains yourdomain.com,www.yourdomain.com --public ~/webapps/yourapp/wordpress/

which made me read the `[]` in the remainder of the README as literal input. 

Anyhow, it works now. Thanks for your kind replies!
