### ISSUE TITLE
Remove "Custom Email Configuration" from README

### ISSUE THREAD

**Issue by donnlee** [will-in-wi/letsencrypt-webfaction#59]
I just got this great tool working for the first time.
One thing that was confusing to me as a new user is the section of the README called "Custom Email Configuration".
I figured out that this is for sending an email to Webfaction Support if you aren't using WF's local Sendmail, but then I realized that v2.0.0 of this tool no longer sends email to WF Support because it uses the WF API and my WF login/password (to install certs).
So that new users don't get confused (like I was), I suggest removing the "Custom Email Configuration" section from the docs/readme.

**Comment by will-in-wi** [comment]
I just pushed a removal of that section of the readme. Thanks for pointing this out!
