### ISSUE TITLE
Invalid account email

### ISSUE THREAD

**Issue by jpdupont** [will-in-wi/letsencrypt-webfaction#60]
Hello, each time I want to run the letsencrypt_webfaction command, I get a invalid 
email account error .
Here I want to renew the certificate, and the first time, 3 mounth ago, the command run fine.

**Comment by will-in-wi** [comment]
You are running an old version. Could you try upgrading to 2.0?

**Comment by jpdupont** [comment]
Thanks, it work now.

For renew, no more cert / key files to paste in the webfaction form ?

**Comment by will-in-wi** [comment]
Correct. As of 2.0, we use the API to automatically upload the new cert.
