### ISSUE TITLE
Automating Renewal

### ISSUE THREAD

**Issue by SNaushadS** [will-in-wi/letsencrypt-webfaction#61]
Hi William,

I would want to automate the renewal of the certs for this i checked the relevant documentation that you have provided.

However, to begin with i need some clarity:

1. I had installed this gem, but i'm unable to understand if it was ruby env or system ruby. How do i check that.

2. Cron,
I read through on how to write a cron sequence.

And i understand i will have to create the below command for all the domains:
`0 4 1 */2 *     PATH=$PATH:$GEM_HOME/bin:/usr/local/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction --letsencrypt_account_email [you@youremail.com] --domains [yourdomain.com,www.yourdomain.com] --public ~/webapps/[yourapp/your_public_html]/`

So do i have to create multiple commands that i can later see in crontab -l ?

Would that be sufficient ?

Also, as a suggestion you may:

1. Rename the Cron to: Automate Renewal, rest content can remain same.

Thanks.

**Comment by SNaushadS** [comment]
I feel ill just have to stick with the standard manual renewal.

Have tried reading, settingup cron and contacting Webfaction support for cron related queries.

**Comment by will-in-wi** [comment]
Hey, sorry for the slow response. With Christmas here, I've been mostly offline on this project for the last couple weeks.

You do indeed have to create multiple cron entries, one for each certificate you want issued/maintained.

Let me know if I can answer any questions which might help!
