### ISSUE TITLE
Not able to renew the ssl certificates

### ISSUE THREAD

**Issue by nijojames92** [will-in-wi/letsencrypt-webfaction#66]
Hi

I'm using lets encrypt ssl certificates for my site hosted in Webfaction server. I followed these steps and it was successfull.

But i'm not able to renew the ssl certificates. i've set the cronjob but its not working. i tried to run the command manually but i'm getting some errors.

Here is the cronjob i've set

System Ruby Installation
```
0 4 1 */1 * PATH=$PATH:$GEM_HOME/bin:/usr/local/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction --letsencrypt_account_email nijo@example.com --domains demo.example.com --public ~/webapps/demo_example/test/
```

RBEnv Installation
```
0 4 1 */1 * RBENV_ROOT=~/.rbenv RBENV_VERSION=2.3.1 ~/.rbenv/bin/rbenv exec letsencrypt_webfaction --letsencrypt_account_email nijo@example.com --domains demo.example.com --public ~/webapps/demo_example/test/
```

i tried to run the commands manually but i'm getting some errors:

```
PATH=$PATH:$GEM_HOME/bin:/usr/local/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction --letsencrypt_account_email nijo@example.com --domains demo.example.com --public ~/webapps/demo_example/test/

/home/nijo/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:69:in validate_options!': Invalid username '' (ArgumentError)
Invalid password ''
from /home/nijo/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:17:inrun!'
from /home/nijo/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/exe/letsencrypt_webfaction:5:in <top (required)>'
from /home/nijo/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:inload'
from /home/nijo/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `'
```

Can someone help me with this

**Comment by will-in-wi** [comment]
As an initial aside, you only need to do either the system ruby OR the rbenv install, not both. Both won't hurt you, but it's superfluous.

The issue appears to be exactly what is reported. You need to add `--username` and `--password` to the command in order for it to run. Better yet, create `~/le_config.yml` containing:

```yaml
username: 'myusername'
password: 'mypassword'
```

And add `--config ~/le_config.yml` to your command instead.

**Comment by nijojames92** [comment]
Hi

I was not able to install rbenv. when i run that command it showing no
permissions to install rbenv in webfaction

**Comment by nijojames92** [comment]
Hi
When i try to run the command manually
PATH=$PATH:$GEM_HOME/bin:/usr/local/bin
GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2
$HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction
--letsencrypt_account_email nijo@example.com --domains demo.example.com
--public ~/webapps/demo_example/test/ --username njio --password cxscxcxcx

it try to access  http URL in
/.well-known/acme-challenge/9W-0Qw32Zn5Fwadkx-OvNsi_XjbhyrVmZh9FtLhPFDY

But currently site webfaction only has https URL served. i'm not getting
any responds  when i'm running this command

**Comment by will-in-wi** [comment]
If I'm understanding correctly, you are having troubles because the domain verification is happening against the http URL, but the site is only being served via https.

This is by design and is a decision made as part of the ACME standard, not this utility. You can either set up the http domain to redirect to the https one, or have the verification happen on the http domain.
