### ISSUE TITLE
Adding a domain to existing app

### ISSUE THREAD

**Issue by fsboehme** [will-in-wi/letsencrypt-webfaction#67]
How would I go about updating the certificate after adding a domain to an existing app?

**Comment by will-in-wi** [comment]
Let's say that your existing command to create a certificate is:

```bash
letsencrypt_webfaction --letsencrypt_account_email me@example.com --domains domain1.example.com --public ~/webapps/myapp --username myusername --password mypassword
```

If so, add an additional domain to the `--domains` args:

```bash
letsencrypt_webfaction --letsencrypt_account_email me@example.com --domains domain1.example.com,domain2.example.com --public ~/webapps/myapp --username myusername --password mypassword
```

Then rerun the command. A new certificate should be generated and saved to your WebFaction control panel.
