### ISSUE TITLE
"If you have several webapps, then you will need to issue the command several times."

### ISSUE THREAD

**Issue by Violet-CLM** [will-in-wi/letsencrypt-webfaction#68]
I'm sorry for the question, but I can't seem to figure out what this line means. Right now my drafted command is simply this:
```
letsencrypt_webfaction --config ~/le_config.yml
```
If I have multiple webapps, do I write this command... and then write it again? How do I know how many times to write it? Or is there something unspecified that I need to change about it each time?

Right now I have multiple webapps, all but one of which are accessible from subdirectories of the basic domain, which has an optional subdomain:

![image](https://cloud.githubusercontent.com/assets/2127931/21916985/118a31fa-d8f9-11e6-8182-e4232420b09f.png)

I figure that for the `--domain` argument I need to list the domain name both with and without the subdomain, e.g. `example.com,myname.example.com'. But how do webapps come into it?

**Comment by ElectricFeet** [comment]
I too was in your position a while back, so I wrote a very basic wiki guide, to teach myself:
https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Wordpress

It could be useful for you. It's written for WordPress WebFaction users. I don't know if you're using WordPress or not, but even if you're not, the concepts will be very relevant to understanding the relationships with WebFaction webapps.

CAVEAT: I haven't updated it since will-in-wi rewrote with the interface to the WebFaction API. Maybe he already did; I'm not sure (I plan to look over it in the next few days). In any case, follow the README for the specific commands, while following the wiki guide for the concepts.

**Comment by Violet-CLM** [comment]
I appreciate the link, but it doesn't seem to address my question at all. The command (with the testing endpoint) creates a `/webapps/carnival/.well-known` folder, but as I noted, my wordpress app is not served at the root folder on my domain, so I get "Failed to verify statuses" and "Invalid response from  http://[my domain]/.well-known/acme-challenge/[long string of characters]" errors. The link makes no mention at all of multiple apps or what the "you will need to issue the command several times" suggestion from the readme might mean.

**Comment by will-in-wi** [comment]
Using the terminology in the WebFaction admin, you will issue the command once per "Website". If you go to the "Websites" tab in the admin UI, you will see the name of the website, the server it sits on, whether or not it is secured, what domains it hosts, and what apps are hosted at what paths.

You will probably run the command once per https application row. Use the list of domains in that row as the list of domains in your command. For the `--public` path, use the application which is on the root (`/`) path, aka `/home/myuser/webapps/appname`.

The verification step will always hit the http version of your domains. So you need them to be redirected to https, or you need to also be serving those webapps from http (I generally suggest the former).

Does this help?

**Comment by Violet-CLM** [comment]
> Using the terminology in the WebFaction admin, you will issue the command once per "Website".

This was the key point, thanks. Django is not much accustomed to serving static files like that, but I was able to setup a symbolic link application at `domain.name/.well-known` pointing at the internal `.well-known` folder, and now everything is working.

In any case, the sentence I was reacting to in the readme really needs to be rewritten. You can't say "webapp" and mean "website" when both of those are technical terms used by the webfaction documentation and internal code with two specific and distinct meanings.

**Comment by will-in-wi** [comment]
Heh, good point. I think I was thinking in more general software development terms when I wrote that. I'll change it. Thanks!
