### ISSUE TITLE
Failed to verify statuses in 10 seconds (redirect is not working)

### ISSUE THREAD

**Issue by atabekm** [will-in-wi/letsencrypt-webfaction#69]
Hi,

I'm currently having a problem with **Failed to verify statuses in 10 seconds.** issue. 

Initially I was very surprised with why script is failing, as I could access newly generated files in /.well-known/acme-challenge/xxx. Later, I found out that those are available only in HTTPS, but not HTTP.

In troubleshooting page, it is written as:

> The file should be accessible on each domain you are trying to create (**redirects appear to be allowed**)

but seems redirect is not working. Is there any way to turn on it, or any easy suggestions to fix the issue (I could go with harder way by turning off https for a while). Thanks in advance.

**Comment by will-in-wi** [comment]
There are some general redirect instructions here: https://docs.webfaction.com/software/static.html#redirect-a-domain-with-a-static-cgi-php-app

The `.htaccess` file I use is this:

```
RewriteEngine On
RewriteCond %{HTTP:X-Forwarded-SSL} !on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```

That way, you can create a generic http redirect app and then reuse it for all of the sites that need a redirect.

Does this help?

**Comment by atabekm** [comment]
Hi,

Sorry, seems my question was not clear enough. I've already redirection implemented on board, I can perfectly access the /.well-known/acme-challenge/xxx from the browser (HTTP is redirected to HTTPS), however seems script itself cannot following redirection rules. My question was, is there any way to tell the script to respect redirection rules?

As an example, if I type 'curl http://mysite.com/.well-known/acme-challenge/xxx' I get something like:

> &lt;p&gt;The document has moved &lt;a href="https://mysite.com/.well-known/acme-challenge/xxx" &gt;here&lt;/a&gt;.&lt;/p&gt;

Thanks.

**Comment by will-in-wi** [comment]
If you then hit `https://mysite.com/.well-known/acme-challenge/xxx` (the destination listed in the http redirect), does it return a 200 response with the contents of the file?

**Comment by atabekm** [comment]
Yes, correct, https one is returning response code 200.

**Comment by atabekm** [comment]
Thanks, the issue has been solved. Seems I was using outdated version, updating to 2.0 solved the problems. Thanks.
