### ISSUE TITLE
Problem with apache mod_wsgi

### ISSUE THREAD

**Issue by Nelkit** [will-in-wi/letsencrypt-webfaction#7]
How use this script with apache mod_wsgi django, always shows this error: `validate!': Failed to verify statuses in 10 seconds. (RuntimeError)

help me please!

**Comment by will-in-wi** [comment]
I'm not familiar with Django, but I assume that there is a folder containing files which are served directly by Apache. You need to make sure that is the folder you are passing in `--public`.

Some more info here: https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Troubleshooting

If that doesn't work, or you figure it out, post back with what you did. I'm collecting a set of notes for specific setups, and I'd love to add Django to the list.

Thanks!

**Comment by will-in-wi** [comment]
From reading the Django docs, I made my best guess at instructions: https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Django

Feel free to give it a shot, and let me know if I should modify the instructions.

**Comment by will-in-wi** [comment]
Have you had any success with getting this to work?

**Comment by diopib** [comment]
I faced the same issue and I have found a workaround:

1. activate https on the django app website
2. add a new static app and create the associated website with the same domain but no ssl
3. use the command with the static app root dir (--public ~/webapps/new_static_app)

After that an email should be sent to support to install the certificate for the specified domain. Et voila.
You can use the newly created static app to redirect http traffic to https as described [here](https://docs.webfaction.com/software/static.html#static-redirecting-from-http-to-https)

**Comment by will-in-wi** [comment]
Thanks for documenting this! I'll try and add this to https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Django when I get some time.

**Comment by Nelkit** [comment]
Very good solution. It works perfect, thanks
