### ISSUE TITLE
Remove .well-known folder after install

### ISSUE THREAD

**Issue by coreyworrell** [will-in-wi/letsencrypt-webfaction#70]
As far as I'm aware, the acme challenge files are not needed after they are used, and they are created new each time the script runs, so I think the the folder should be removed after a successful run.

**Comment by will-in-wi** [comment]
This is a good idea. I'll add it to the roadmap for when I dive back into the code. For the time being, the files are so small, it doesn't hurt to have them hang around.

**Comment by will-in-wi** [comment]
Thanks for the suggestion!
