### ISSUE TITLE
Only renew if neccessary

### ISSUE THREAD

**Issue by coreyworrell** [will-in-wi/letsencrypt-webfaction#71]
The certbot service encourages the use of a twice a day cron job that will first check if a new cert is needed before requesting and installing one. This makes it useful if a cert were ever revoked for any reason, as well as making full use of the 90 day certs.

With letsencrypt-webfaction, your docs say to setup a cron job that runs every two months, so in this case you aren't getting the "full use" out of your certs. This isn't a problem, but it does feel like an unnecessary restriction.

Perhaps the script could check the current cert's expiration date, and if it is not within a few days of needing renewal then it could just exit out.

The script works great as-is though, this was just a thought for minor improvement. Thanks for your hard work!

**Comment by will-in-wi** [comment]
That's certainly a great idea. I considered it initially, but decided that the added complexity wasn't worth it at the time.

At this point, I keep hoping that WebFaction will finally release their much overdue and announced first-party LetsEncrypt support. When (if?) that happens, this utility becomes unneeded.

There are a variety of other user-friendlyness improvements that I'd like to make if I were to maintain this long term. I'll add this to the list.

As always, if you or someone else wants to make a pull request with this feature, I'd certainly be happy to work to get it merged.

I just put together a roadmap page on the wiki to hopefully act as a feature request clearing house for stuff like this. https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Roadmap

Thanks for the suggestion!
