### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by cguerrave** [will-in-wi/letsencrypt-webfaction#72]
Hi! I have just upgraded to version 2.0.0

I am trying to renew certificates and having this output:
```
/home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/args_parser.rb:130:in `parse!': undefined method `any?' for #<String:0x000000018f4138> (NoMethodError)
	from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/args_parser.rb:49:in `initialize'
	from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:12:in `new'
	from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:12:in `initialize'
	from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/exe/letsencrypt_webfaction:5:in `new'
	from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/exe/letsencrypt_webfaction:5:in `<top (required)>'
	from /home/myuser/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/myuser/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

I user command line params and config.yml and nothing, I'm not having certs in le_certs/ nor in the webfaction panel, it seems that it not start the process, maybe I'm doing something wrong?

Thank you very much for doing this tool, i have used it since several months and is super useful!

**Comment by will-in-wi** [comment]
It looks like there is an issue with the contents of the `--domain` argument. Do you have one? Could you post an anonymized version of what you are using?

Thanks

**Comment by cguerrave** [comment]
Ok, when I was using the config file it was like this:

```
#config.yml
key_size: 4096
# We need an ACME server to talk to, see github.com/letsencrypt/boulder
endpoint: 'https://acme-v01.api.letsencrypt.org/'
domains: mydomain.com,mydomain.org,mydomain.xyz,www.mydomain.com,www.mydomain.org,www.mydomain.xyz
public: '~/webapps/myapp/'
output_dir: '~/le_certs/'
letsencrypt_account_email: 'carlos@mydomain.org'
api_url: 'https://api.webfaction.com/'
username: 'myuser'
password: 'mypw'
servername: ''
cert_name: ''
```

And I just copied and pasted the domain field when using the command without config file and the error was different (webfaction API related), in the end I could avoid the error and renew the cert using another config file just with my user and password and the rest of the fields written as command parameter, this way:

```
#newconfig.yml
username: "myuser"
password: "mypw"
```

```
#command
letsencrypt_webfaction --config newconfig.yml --letsencrypt_account_email carlos@mydomain.org --domains mydomain.com,mydomain.org,mydomain.xyz,www.mydomain.com,www.mydomain.org,www.mydomain.xyz --public ~/webapps/myapp/
```

I hope this can help you somehow to debug the possible source of the error, sorry for not documenting better this issue (I was in a hurry :S ) and for the english.. Thank you again for this super useful tool!

**Comment by will-in-wi** [comment]
Could you try making the `domains` part of the config file singular? e.g. `domain`?

**Comment by cguerrave** [comment]
Still with errors:

```
/home/user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:69:in `validate_options!': Invalid domains '[]' (ArgumentError)
Invalid cert_name ''
	from /home/user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:17:in `run!'
	from /home/user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/exe/letsencrypt_webfaction:5:in `<top (required)>'
	from /home/user/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/user/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

At least I know how to make it work with the solution of just using user and pw in the config and the rest in params :)

**Comment by will-in-wi** [comment]
Hmm. My advice earlier was wrong. You are correct that the param is plural...

Could you try using:
```yaml
domains:
  - mydomain.com
  - mydomain.org
  - mydomain.xyz
  - www.mydomain.com
  - www.mydomain.org
  - www.mydomain.xyz
```

as your domains line in the config?

Also, you will want to either provide a value for servername and cert_name or omit them entirely from the config.

**Comment by will-in-wi** [comment]
@cguerrave: I'm closing this ticket due to its age. If you are still running into issues, feel free to reopen it!
