### ISSUE TITLE
Beginners issue

### ISSUE THREAD

**Issue by janlimpens** [will-in-wi/letsencrypt-webfaction#74]
Hello, 

I am certain this has nothing to do with your programming, but when I follow your installation steps from "System.Ruby", I can run letsencrypt-webfaction from the command line, but once I run it from a separate script, as you suggest, I get a 
```
-bash-4.1$ bash ./letsencrypt/command
./letsencrypt/command: line 1: letsencrypt_webfaction: command not found
```
So something seems to missing here...

Big thanks,
Jan

**Comment by asgaines** [comment]
I'm guessing your PATH isn't set up properly. You should be able to get around this by using the full path to the executable: `/home/<youraccount>/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction` instead of only using `letsencrypt_webfaction` in your script.

**Comment by will-in-wi** [comment]
@janlimpens: I'm closing this due to its age. If you are still having trouble, feel free to reopen.

**Comment by janlimpens** [comment]
I think the thing was just due to .bash_profile IMHO not being loaded on non interactive sessions.

**Comment by will-in-wi** [comment]
Ah, that would make sense. Glad to hear you got it working!
