### ISSUE TITLE
Parameters documentation

### ISSUE THREAD

**Issue by janmechtel** [will-in-wi/letsencrypt-webfaction#76]
Found and love this, just trying this now and try to contribute. 

I can't find any documentation on these to params from [config.defaults.yml](https://github.com/will-in-wi/letsencrypt-webfaction/blob/master/config.defaults.yml)

`servername: ''`
`cert_name: ''`

Should they be removed or explained somewhere?

**Comment by janmechtel** [comment]
I found the answer to both by calling 

```
letsencrypt_webfaction --help 
       --servername=SERVERNAME      The server on which this application resides (e.g. Web123).
        --cert_name=CERT_NAME        The name of the certificate in the Webfaction UI.

```

**Comment by janmechtel** [comment]
I'm still unclear what the CERT_NAME in Webfaction UI means

**Comment by will-in-wi** [comment]
All caps means you fill in your own value for it.
