### ISSUE TITLE
Not able to renew my SSL certificates in Webfaction

### ISSUE THREAD

**Issue by nijojames92** [will-in-wi/letsencrypt-webfaction#77]
Hi 

I'm using lets encrypt SSL certificates for my domain test.com and for its two sub domains one.test.com and two.test.com. they are in different webfaction servers so i had to create separate SSL certificates for them. I followed this doc to generate the ssl certificates and it worked but to renew the ssl certificate i used the following command:

`letsencrypt_webfaction --letsencrypt_account_email test@domain.com --domains test.com --public /home/user/webapps/test/your_public_html --username user --password WEbfaction_password`

This command regenerates a new ssl certificate in the webfaction console, i did this to renew 2 SSL certificates so currently they have issued 5 SSL certificates. 

But now i'm not able to renew the same. getting some rate limit error
https://community.letsencrypt.org/t/not-able-to-renew-ssl-certificates-of-sub-domains/29923
https://letsencrypt.org/docs/rate-limits/

Is there any way to renew my ssl certificates.

**Comment by hyperpress** [comment]
Unfortunately, ther rate limits is set by LE on a per five day basis. So until five days have elapsed there is nothing to be done.  I feel your pain, but I run a test command first using the sandbox target example provided to make sure it is working, and set the crown to email us if it fails on the cron..

**Comment by nijojames92** [comment]
But the last time i renewed it was 2 months ago. Now i'm not able to renew any of my ssl certificates. I'm getting the same error.

/home/user/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client/faraday_middleware.rb:43:in raise_on_error!': Error creating new cert :: Too many certificates already issued for exact set of domains: one.test.com (Acme::Client::Error)
from /home/user/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client/faraday_middleware.rb:33:inon_complete'
from /home/user/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client/faraday_middleware.rb:18:in block in call'
from /home/user/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/response.rb:57:inon_complete'
from /home/user/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client/faraday_middleware.rb:18:in call'
from /home/user/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:inbuild_response'
from /home/user/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in run_request'
from /home/user/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:177:inpost'
from /home/user/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client.rb:68:in new_certificate'
from /home/user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:42:incertificate'
from /home/user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:34:in certificate_installer'
from /home/user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:26:inrun!'
from /home/user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/exe/letsencrypt_webfaction:5:in <top (required)>'
from /home/user/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:inload'
from /home/user/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `


so you are telling that i should wait for 5 days and then try to renew them

**Comment by hyperpress** [comment]
Yes. Let's Encrypt is replying back with the error, and it's saying that you have exceeded the rate limit for the number of certificates that can be issued for the domain(s) in the run. It may be that you either accidentally ran the command more than five times within the five day window (either from the command line in a shell, or from the crontab that was setup. I don't know. But that's why it's failing. Once you hit the rate limit, it's locked for five days and their is nothing you can do to unlock it accept wait for the period to pass. I wish there was better news, but it's a rule they have to prevent their servers from being overrun with bad scripts and DNS attacks.

**Comment by will-in-wi** [comment]
@nijojames92 sorry, but @hyperpress is right. However it has happened, you hit the API limits and can only wait for them to expire. In future, the sandbox is useful for testing as it doesn't have the same limits. I hope this script has proved useful besides that!

@hyperpress: Thanks for helping out!
