### ISSUE TITLE
redirect_to_https

### ISSUE THREAD

**Issue by just-us** [will-in-wi/letsencrypt-webfaction#79]
Hi guys,

Just wondering if we would need to create a redirect to https site for each website that we are looking after or if this one thing can have multiple sites attached to it?

**Comment by will-in-wi** [comment]
I personally have the latter approach. I create one http website with the following htaccess:

```ApacheConf
RewriteEngine On
RewriteCond %{HTTP:X-Forwarded-SSL} !on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```

Then I add all domains I want redirected to https to this website.
