### ISSUE TITLE
Error log?

### ISSUE THREAD

**Issue by richardpenman** [will-in-wi/letsencrypt-webfaction#80]
I set this up to run in cron and it worked great, however the latest update didn't create the certificate files. Is there an error log to help identify what is going wrong?

**Comment by hyperpress** [comment]
I've not encountered problems from update. If you run the same command using sandbox target from CALI, is there any output you can share?

**Comment by hyperpress** [comment]
Auto correct 😠

I meant from CLI.

**Comment by richardpenman** [comment]
There is no output or errors to indicate what is wrong, but the same settings before produced a new certificate.

**Comment by will-in-wi** [comment]
Not sure what happened here. In the cron usage section, there's a note as to how you can use `MAILTO` to get an email whenever anything in cron outputs to standard out or standard error. That might be helpful in future.
