### ISSUE TITLE
From the docs it's not clear why and when password is needed

### ISSUE THREAD

**Issue by andybak** [will-in-wi/letsencrypt-webfaction#81]
You don't mention that it's optional but then it's not included in the cron example.

Is it needed for the initial cert but not for renewals? I'm guessing it's needed for Webfaction API calls that are only used for the first setup  but it would be useful if this was made explicit.

**Comment by hyperpress** [comment]
You do need to pass the username and control panel in the cron. You may
want to look at using file for the cron instead. But yes they are required.

**Comment by will-in-wi** [comment]
@andybak Thanks for pointing this out! @hyperpress is right, the username and password are required, however, not including them in the default example is an oversight on my part, which I will correct.

**Comment by will-in-wi** [comment]
@andybak: I just pushed https://github.com/will-in-wi/letsencrypt-webfaction/commit/ce7e083905435bc1c3a8f2bd82e4634bb9a77bfc which should help. If you have any comments about it, feel free to reopen this ticket with them. Thanks!
