### ISSUE TITLE
Not allowed to login to machine

### ISSUE THREAD

**Issue by hellvix** [will-in-wi/letsencrypt-webfaction#82]
Any ideas why am I getting this error? How should the server name be? I tried "webX" and "webX.webfaction.com" and didn't work.

```
$ letsencrypt_webfaction --config ~/webfaction_letsencrypt_files/config.defaults.yml

/usr/local/lib/ruby22/ruby/2.2.0/xmlrpc/client.rb:271:in `call': Not allowed to login to machine "webX" (XMLRPC::FaultException)
	from /home/user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/certificate_installer.rb:33:in `session_id'
	from /home/user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/certificate_installer.rb:14:in `install!'
	from /home/user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:26:in `run!'
	from /home/user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/exe/letsencrypt_webfaction:5:in `<top (required)>'
	from /home/user/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/user/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

```
[user@webXYW webfaction_letsencrypt_files]$ cat config.defaults.yml 
key_size: 4096
# We need an ACME server to talk to, see github.com/letsencrypt/boulder
# endpoint: 'https://acme-v01.api.letsencrypt.org/'
endpoint: 'https://acme-staging.api.letsencrypt.org/'
domains: [domain1.com,www.domain1.com,subdomain.domain1.com,domain2.com,www.domain2.com]
public: '/home/user/webapps/applications_https_redirect'
output_dir: '~/le_certs/'
support_email: 'webmaster@domain.com'
letsencrypt_account_email: 'webmaster@domain.com'
api_url: 'https://api.webfaction.com/'
username: 'user'
password: 'password'
servername: 'webX'
cert_name: 'domain_certificate'
```

I am using version **2.0.0**.

**Comment by hyperpress** [comment]
Check https://docs.webfaction.com/user-guide/server.html for details on how
to find your server details.

**Comment by hellvix** [comment]
Yeah, that is correct. I tried: **webX** and the server name plus the domain **webX.webfactionl.com**. Still the same error message.

**Comment by hyperpress** [comment]
Just needs the correct subdomain prefix for server name. So, it's likely
related password. Assuming you are using your control panel password?

If you run the command straight from CLI instead of using file method does
it work?

On Apr 12, 2017 4:14 AM, "hellvix" <notifications@github.com> wrote:

Yeah, that is correct. I tried: *webX* and the server name plus the
domain *webX.webfactionl.com
<http://webX.webfactionl.com>*. Still the same error message.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/will-in-wi/letsencrypt-webfaction/issues/82#issuecomment-293520170>,
or mute the thread

**Comment by hellvix** [comment]
I get the same error.

**Comment by hyperpress** [comment]
Have a look at
https://github.com/will-in-wi/letsencrypt-webfaction/issues/63

This could be the cause.

**Comment by hellvix** [comment]
This is how I am running the command:

`letsencrypt_webfaction --config ~/webfaction_letsencrypt_files/config.defaults.yml`

Also, the error seems to be in the authentication.

**Comment by will-in-wi** [comment]
Glad to hear it worked for you in the end!
