### ISSUE TITLE
Add user/pass to cron job example

### ISSUE THREAD

**Issue by bobtiki** [will-in-wi/letsencrypt-webfaction#84]
Since, as you say in issue #81, that the user name and password are required for the cron job, I suggest those be added to the example cron command. It's unclear why they're left out there, and folks new to the process (like me!) may wonder a couple of months later why their certificate just expired and didn't renew, since they followed the example.

(Thanks so very much for this script — it has saved me a ton of grief! Just that one remaining thing I stumbled over, until I searched through the closed tickets.)

**Comment by will-in-wi** [comment]
Very good point. I'll fix this.

**Comment by billythekid** [comment]
Possibly worth mentioning that if your password includes special chars it'll need to be input in single quotes, something like

```
0 0 0 */2 * letsencrypt_webfaction --letsencrypt_account_email YOUR_EMAIL_FOR_THIS_CERT --domains YOUR_DOMAIN,WWW.YOUR_DOMAIN --public /PATH/TO/YOUR/PUBLIC/WEB/FOLDER --username YOUR_USER_NAME --password 'YOUR_PASSWORD_IN_SINGLE_QUOTES'
```

Also, I've yet to get this to work as a CRON job, even with the letsencrypt_webfaction binary folder added to my PATH like this at the top of my crontab:
```
GEM_HOME=/home/YOUR_USER_NAME/.letsencrypt_webfaction/gems
PATH=$PATH:$GEM_HOME/bin
```

Any ideas on what I'm doing wrong or missing here?

**Comment by will-in-wi** [comment]
The original ticket was fixed in https://github.com/will-in-wi/letsencrypt-webfaction/commit/f2a9531f5195f450ff93d360462a59cd25456889.
