### ISSUE TITLE
Webfaction Django issue serving .well-known dir Apache

### ISSUE THREAD

**Issue by ionescu77** [will-in-wi/letsencrypt-webfaction#85]
Hi,

the way I setup my django projects on webfaction leaves me with all static data served under:
mydomain.com/static

This did not work with our script. I found a [workaround on stackoverflow](http://stackoverflow.com/questions/38443572/using-lets-encrypt-without-control-over-the-root-directory):

Just added this to the apache config:

```
Alias /.well-known/ /home/user/webapps/XXXXX/website/static/.well-known/
<Directory /home/user/webapps/XXXXX/website/static/.well-known/>
Require all granted</Directory>
```

So all my django static assets are still available under /static/, and only for letsencrypt.

Thank you for this will-in-wi

**Comment by ionescu77** [comment]
I will also set it to close, however if anyone encounters the same problem they can check closed issues (I did, however most of the titles where not self explanatory)

**Comment by will-in-wi** [comment]
This is great, thanks! I added a link to this ticket in https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Django
