### ISSUE TITLE
Using test endpoint generated certificates. Why?

### ISSUE THREAD

**Issue by vegemite4me** [will-in-wi/letsencrypt-webfaction#87]
Hi,
 I thought I was using the test `endpoint`, but after executing `letsencrypt_webfaction` I can see a certificate for this particular domain when I go to the SSL Certificates page in the Webfaction control panel. Why did this happen when I was using the test endpoing?
 Have I misunderstood something?
Robin

The command I ran:

`letsencrypt_webfaction --config ~/le_config.yml --domains example.co.uk,www.example.co.uk --public ~/webapps/example/
`

This is my le_config.yml:

```
key_size: 4096
# We need an ACME server to talk to, see github.com/letsencrypt/boulder
endpoint: 'https://acme-v01.api.letsencrypt.org/'
#domains: []
#public: ''
output_dir: '~/le_certs/'
letsencrypt_account_email: 'me@example.com'
api_url: 'https://api.webfaction.com/'
username: 'myusername'
password: 'mypassword'
servername: ''
cert_name: ''
```

**Comment by will-in-wi** [comment]
The test endpoint issues certificates from Let's Encrypt's test root certificate. It will install it in the WebFaction admin interface so that you can test it if you want. 

When it works, you can re-run the command without the test endpoint and it will overwrite the test certificate.

**Comment by vegemite4me** [comment]
OK, that makes complete sense. Thank you.
