### ISSUE TITLE
Certificate not activated on website without manual intervention

### ISSUE THREAD

**Issue by gajama** [will-in-wi/letsencrypt-webfaction#88]
Hi,
It's a great tool and works well. But I find that although the certificate gets updated in the list of SSL certificates at https://my.webfaction.com/ssl-certificates it does not actually update the certificate used by the website which continues to use the previous certificate.
I have to go to the website list at https://my.webfaction.com/websites select the website I've just updated the cert for and then save the record (without making any changes) for the new certificate to actually be used. I noticed this this morning when one of my websites started showing a certificate error despite the cert being updated last week.
I was expecting that updating the certificate would mean that the new cert got used without this manual step.
Is this the general experience and this is working as expected, or should I actually not need to perform this manual step?

**Comment by will-in-wi** [comment]
This should work as you expect. When the new certificate it uploaded to the certificate record in the WebFaction admin, any websites configured to use it should automatically update to the new certificate. I'd suggest you open a ticket with WebFaction, as something on their end isn't working correctly.
