### ISSUE TITLE
On success 0 exit code, then what?

### ISSUE THREAD

**Issue by cwhitten** [will-in-wi/letsencrypt-webfaction#89]
Shouldn't I expect to see .key and .pem files generated somewhere?

**Comment by cwhitten** [comment]
disregard!

**Comment by will-in-wi** [comment]
In case anyone else hits this ticket and wonders what the answer is, the key and pem files are automatically uploaded to the WebFaction control panel without any temporary files being created on disk.

I'm glad this tool is proving useful to you!
