### ISSUE TITLE
Issuing certs for 2 domains results in timeout for second domain

### ISSUE THREAD

**Issue by reconfine** [will-in-wi/letsencrypt-webfaction#90]
seeing an issue when I run a test certificate command for more than one domain at a time (eg domain.com,www.domain.com), it appears that the verification for the second domain times out with the following message. 

```
failed to verify statuses
domain.com success
fetching http://www.domain.com/.well-known/acme-challenge/xxxxx: timeout
make sure that you can access http://www.domain.com/.well-known/acme-challenge/xxxxx
```

Have checked and file is successfully created for both domains, and command runs successfully if I only specify one domain at a time. Any ideas?

**Comment by reconfine** [comment]
Issue also occurs for calls to live cert server

**Comment by will-in-wi** [comment]
Would you share the anonymized version of the command you are running?

**Comment by reconfine** [comment]
`letsencrypt_webfaction --domains xxxxx.com,www.xxxxx.com --public ~/webapps/xxxxx/ --endpoint https://acme-staging.api.letsencrypt.org/ --config /home/xxxxxx/le_certs/config.yml`

Successfully verifies first domain specified, but times out on the second domain specified even if I reverse the order they are specified in.

**Comment by will-in-wi** [comment]
That's really odd… I'm not sure I even have a guess as to the issue…

When you run this, do you see Let's Encrypt accessing the files on both domains in your frontend logs?

**Comment by ralfzen** [comment]
Hi there,
I got the same issue when running the above with the current version ``2.2.1``. When I access the ``.well-known/acme-challenge/<hash>`` it's there, but letsencrypt_webfaction always shows **Timeout**.
I would appreciate any hints on this?

**Comment by will-in-wi** [comment]
@ralfzen, could you open a new ticket with this issue?

Thanks!

**Comment by ralfzen** [comment]
Hi @will-in-wi,

thanks for the fast response. I am currently writing the answer.
The problem was in the DNS-Settings of the requested domain. There was a wrong IPv6 in the ``AAAA-Record``. So ``letsencrypt_webfaction`` stucked and returned a timeout, when requesting the acme-challenge. It would more bulletproof, if it would change to IPv4 in second instance I think. Or if there would be a more verbose ``DEBUG``-option.
But thanks anyway. Now it's working 👍

**Comment by will-in-wi** [comment]
Glad to hear you got it figured out!
