### ISSUE TITLE
Uninstall and remove certs

### ISSUE THREAD

**Issue by miloszorica** [will-in-wi/letsencrypt-webfaction#91]
How do I uninstall letsencrypt_webfaction and remove SSL certificates it created?

**Comment by will-in-wi** [comment]
You can remove the certs in the WebFaction control panel. To remove letsencrypt_webfaction, delete the relevant entries from your crontab, and then you can delete the `$HOME/.letsencrypt_webfaction` folder.

**Comment by ElectricFeet** [comment]
Hi Will!
I note that there is also a `.gem` folder. How does one go about uninstalling the Ruby stuff that was installed as a pre.req?
