### ISSUE TITLE
Too many websites

### ISSUE THREAD

**Issue by mikemand** [will-in-wi/letsencrypt-webfaction#95]
Hello,

I host 50+ websites (about 1/3 of those are for development purposes, the other 2/3 are only counting the bare domain name, they also serve the www. domain name too).

Is there some way I can get a certificate for all of them at once? With the new rate limit (at least, new within the last 3 months) I am unable to renew more than 5 of my domains within a 5 day period, which is not going to work because *all* of my certificates need to renew tomorrow...

**Comment by hyperpress** [comment]
That's a Let's Encrypt limit, not the Webfaction LE Tool. My understanding
is that LE will be offering wildcard certs beginning in Jan 18.

**Comment by mikemand** [comment]
Wildcard certs will be a blessing, but that's still 4 months away. I'm asking if there is any way I can renew all of my certificates (or at least 30 of them, the production ones) by tomorrow. Their [rate limiting](https://letsencrypt.org/docs/rate-limits/) documentation is confusing to me. What is an account? I've only ever run this script to get certificates, I don't remember ever setting up an account.

I am *not* a server admin (thus why I use WebFaction), so anything beyond running a simple command is beyond me.

**Comment by will-in-wi** [comment]
If I understand correctly, an Account is the email address you provide to them when you create the cert, specifically, that's what the `--letsencrypt_account_email` param is for.

There are a number of options depending on your exact setup. If you are talking about 30+ "Registered Domains", I don't think that there are any limitations with regards to that. If you have multiple certs per registered domain, you may have a problem.

Either way, depending on how your apps work, you may be able to generate a single UCC cert (where you have a bunch of domains in one certificate).

Could you share more about your setup? If you want to do so privately, you could directly message me.

**Comment by ThemeSurgeon** [comment]
There's no way round the per domain rate limit. You'll probably need to investigate a wildcard cert via namecheap or similar SSL provider until the feature is available.

**Comment by mikemand** [comment]
Hi Will,

Yes, I have about 30 registered domains. Each registered domain has its own website and application in WebFaction. There is one certificate for `domain.com` and `www.domain.com` together. If I need a development "staging" area for a site, I also generate a certificate for `dev.domain.com`. 3 of the sites also have a blog hosted at `blog.domain.com`, which is run on a separate website and application in WebFaction.

**Comment by mikemand** [comment]
I should also note that the error I'm getting is this: `Error creating new registration :: too many registrations for this IP (Acme::Client::Error)`. Maybe it wasn't even me that did it, but someone else on my server?

**Comment by will-in-wi** [comment]
The way you have your apps set up shouldn't be an issue. There is no limit on registered domains, and you have a maximum of three certs per registered domain, well below the 20 cert limit.

The error is informative. I'm guessing the rate limits that apply are the following:

> You can create a maximum of 10 Accounts per IP Address per 3 hours. You can create a maximum of 500 Accounts per IP Range within an IPv6 /48 per 3 hours. Hitting either account rate limit is very rare, and we recommend that large integrators prefer a design using one account for many customers.

I'm guessing that you are correct, and someone else on the server or IP range is requesting a pile of certs. Thankfully, you are only dealing with a three hour sliding window, so hopefully you can get the apps set up by tomorrow. Maybe wait three hours and try again?

I'd suggest in future, setting up certificate renewal in a staggered way, so that you are renewing a cert every other day or so, rather than in one big batch. This makes it less likely that you will run into issues. Renew the whole batch now, since you need this done, and then when you set up all of your cron tasks, vary the day of the month it runs on. https://crontab.guru/ is helpful for figuring out the best syntax.

**Comment by mikemand** [comment]
I still have a couple minutes before I can try to renew again, so we'll see what happens.

Looking back through their rate limiting document, it looks like they are suggesting renewal 30 days before the certificate expires (this wasn't the case when I started using Let's Encrypt, LOL). After this batch of renewals, I will set up cron to run 1 domain per day starting 60 days after today/tomorrow.

I went ahead and opened a support ticket with WebFaction to see if they can request an exemption (at least for my server) so I can get these domains renewed. They have not responded yet, but we'll see.

**Comment by mikemand** [comment]
WebFaction didn't notify me, but it looks like they've fixed the problem. I am able to renew my certificates now. :)

Thank you @will-in-wi and @hyperpress / @ThemeSurgeon

**Comment by mikemand** [comment]
Spoke too soon. I got 10 of them renewed before the rate limit hit again. Ugh.

**Comment by will-in-wi** [comment]
@mikemand I just pushed v2.1.0 which now includes the ability to provide multiple public directories allowing a single cert to cover multiple applications. This might help.

**Comment by mikemand** [comment]
Thank you! I will look into that as a possible alternate solution
