### ISSUE TITLE
Contributing a simple change to support multiple websites & public_html dirs per cert!

### ISSUE THREAD

**Issue by lsemprini** [will-in-wi/letsencrypt-webfaction#96]
Hi,

Thanks so much for making letsencrypt-webfaction...it's awesome!

Here is a very very simple, backwards-compatible change that will greatly increase the audience who can get benefit from letsencrypt-webfaction

I have provided both code and documentation below.

Like many users, I have so many websites under one account that creating separate certificates for them requires a downright silly level of workarounds and coordination due to Let's Encrypt's (understandable) rate limiting system.

But in reality, in many cases it would be MUCH simpler and easier just to create one cert for all domains.  Rather than playing games spreading my cert registrations over time to avoid rate limiting, I can just create a SINGLE cert (which only counts as one request from Let's Encrypt's point of view, so rate limiting is not an issue at all), and another benefit is that I have fewer files and cases to manage too.  Let's Encrypt supports up to 100 hostnames per cert.

letsencrypt-webfaction can ALMOST do this...it's SO close....but currently it assumes there is only one "public-html" directory for all websites in the cert.

Here is a very very simple change that expands the --public argument from a string to a comma-separated list.  When letsencrypt-webfaction is doing the http01 challenge-response, it simply copies all challenge files to all public directories.  Yes, this is more copying than necessary, but they are tiny files and the storage is totally irrelevant, and it means we can retain a simple, backwards-compatible command-line that doesn't require telling letsencrypt-webfaction which directory goes with which domain(s) (which is difficult because the mapping is not necessarily 1:1).

With this one magical change, I was able to create a single cert for ~40 websites spread around ~18 different public directories.

I encourage you to take this change into your master tree.  I think it will help a lot of people.

The only issue I could think of is that if someone was using letsencrypt-webfaction with a filename containing a comma, it would be interpreted differently by this new version.  If you want to avoid that problem, you can instead add a --publics argument that is an alternative to --public that expects comma-separated input.  But it's probably not a big deal.

Sorry I am not well-versed in submitting "pull requests" and patches.  But the change is so simple I can just list it here:

CHANGE 1: config_defaults.yml
from
`public: ''`
to:
`public: []`

CHANGE 2: lib/letsencrypt_webfaction/args_parser.rb
from
`Field.new(:public, 'Location on the filesystem served by the desired site (e.g. ~/webapps/myapp/public_html)', [StringValidator.new]),`
to
`Field::ListField.new(:public, 'Locations on the filesystem served by the desired sites (e.g. ~/webapps/myapp1/public_html,~/webapps/myapp2/public_html)', [ArrayValidator.new]),`

CHANGE 3: lib/letsencrypt_webfaction/domain_validator.rb
from
`def initialize(domains, client, public_dir)`
to
`def initialize(domains, client, public_dirs)`

from
`@public_dir = File.expand_path(public_dir)`
to
`@public_dirs = public_dirs.map { |dir| File.expand_path(dir) }`

from
```
        challenges.each do |challenge|
        # Save the file. We'll create a public directory to serve it from, and we'll creating the challenge directory.
        FileUtils.mkdir_p(File.join(@public_dir, File.dirname(challenge.filename)))

        # Then writing the file
        File.write(File.join(@public_dir, challenge.filename), challenge.file_content)
      end
```
to
```
      challenges.each do |challenge|
        @public_dirs.each do |public_dir|
          # Save the file. We'll create a public directory to serve it from, and we'll creating the challenge directory.
          FileUtils.mkdir_p(File.join(public_dir, File.dirname(challenge.filename)))

          # Then write the file
          File.write(File.join(public_dir, challenge.filename), challenge.file_content)
        end
      end
```
That's it!

I would add the following documentation in the README.md under Usage ... Options .. --public at the end of the existing --public description:

You can actually specify multiple public directories in this option, separated by commas.  This is useful when you want to create a single certificate that serves multiple domains that happen to be backed by multiple different public directories.  During Let's Encrypt's http01 challenge-response, letsencrypt-webfaction will copy all the challenge files for all domains into all the public directories, which means the order in which you specify directories doesn't matter (it doesn't have to match the order of the domains you specify).  It also means that technically you will end up with more small challenge files than necessary in each public directory (challenge files go into the directory `/.well-known/acme-challenge/...` under each public directory) but this is unlikely to be an issue as they are tiny files.  Let's Encrypt supports up to 100 domains per certificate, and they discuss the pros and cons of the multiple-domain technique here: https://letsencrypt.org/docs/integration-guide/

Thanks!

**Comment by will-in-wi** [comment]
On its face, this is a good idea. It would have helped https://github.com/will-in-wi/letsencrypt-webfaction/issues/95 quite a bit.

I'll look into creating a PR out of your comments and then you can confirm that it was what you were thinking.

Thanks!

**Comment by will-in-wi** [comment]
I just pushed v2.1.0 which contains this change. Thanks for the suggestion!

**Comment by lsemprini** [comment]
Cool thanks!
