### ISSUE TITLE
Bug when I execute the script

### ISSUE THREAD

**Issue by jpdupont** [will-in-wi/letsencrypt-webfaction#98]
Hello, I execute the script  and I get no certificates and this lines :

```
$ letsencrypt_webfaction --config ~/le_config/config.commune.yml
/home/rouvroy/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.2.0/lib/letsencrypt_webfaction/domain_validator.rb:8:in `initialize': undefined method `map' for "~/webapps/commune/":String (NoMethodError)
        from /home/rouvroy/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.2.0/lib/letsencrypt_webfaction/application.rb:61:in `new'
        from /home/rouvroy/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.2.0/lib/letsencrypt_webfaction/application.rb:61:in `validator'
        from /home/rouvroy/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.2.0/lib/letsencrypt_webfaction/application.rb:29:in `run!'
        from /home/rouvroy/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.2.0/exe/letsencrypt_webfaction:5:in `<top (required)>'
        from /home/rouvroy/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
        from /home/rouvroy/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

Where I'm wrong ?
Thanks for the help

**Comment by will-in-wi** [comment]
I accidentally changed the format of the `public` configuration key from a string to an array in version 2.1.0. I just pushed 2.2.1 which supports both the string and array usages, so your config should work there.

In summary, you have two fixes:

1. Change your config file so that the `public` key contains an array value:

```yaml
public: ['mypath']
# OR
public:
  - 'mypath'
```

2. Upgrade to 2.2.1.

**Comment by jpdupont** [comment]
It worked as expected! Great thanks for your quick help.

**Comment by jpdupont** [comment]
I write this in the configuration file
**output_dir: '~/le_certs/'**
 but the certificates go into the "certificates" folder. What is the problem ?

**Comment by will-in-wi** [comment]
As of 2.0, certificates are installed in the webfaction admin interface and not stored on disk.

**Comment by jpdupont** [comment]
William, thanks for the help ! 

Last problem, with the crontab ...

My crontab commands below work when I run them **out the crontab**. My certificates are well generated and introduced into the panel. 

I had configured the crontab for it to fire today at 1:00, but nothing happened. No email sent, and no certificate renewal.
Can you tell me what is wrong here?

My crontab :

MAILTO="jean.pol.dupont@alysse.info"
MAILFROM="jp@alysse.info"
0 1 2 */2 *   letsencrypt_webfaction --config ~/le_config/config.commune.yml
0 1 2 */2 *   letsencrypt_webfaction --config ~/le_config/config.billetterie.yml
0 1 2 */2 *   letsencrypt_webfaction --config ~/le_config/config.lerox.yml
