### ISSUE TITLE
Finding a way to make this work without having to supply the password.

### ISSUE THREAD

**Issue by Scott-MacD** [will-in-wi/letsencrypt-webfaction#99]
Any thoughts on finding a way to make this work without having to supply the password?

We ran into the scenario this morning where our site was effectively offline due to being blocked in browsers due to an expired certificate. This was caused by the cronjob failing to renew the certificate due to an incorrect password, which in turn, was due to us having to change our password a couple weeks ago, and us forgetting about this script being dependant on these credentials.

Of course after this experience we've made sure it is well documented and this information has been passed throughout our dev team, however it still seems like a bad idea that if this ever gets forgotten about again, and we update our account credentials without updating the script, all our sites relying on it will run into crippling certificate errors again.

**Comment by will-in-wi** [comment]
This has been somewhat covered in https://github.com/will-in-wi/letsencrypt-webfaction/issues/64

In short, the only API authentication option Webfaction provides us is username/password. This is pretty awful, but I don't have anything better...

I'd suggest a workaround of adding `MAILTO=youremail@yourdomain.com` to the top of your crontab. Then you will get emailed in case of renewal failure.

**Comment by will-in-wi** [comment]
There are also services which will monitor your domains and warn you if they are getting too close to expiration. I don't have any particular recommendations, but depending on your site's importance, it might be a worthwhile investment.

**Comment by Scott-MacD** [comment]
Thanks for the response Will.

I've adjusted how often the cron job runs and added some failure logs, so that should help for now. Is there any reason specifically that this has to run through the webfaction API instead of directly dealing with the file system, and/or running commands directly off the server?

I'm not expecting you to write it by any means, but just a thought I might explore myself once I have some down time, unless you know of any roadblocks that would require the API.

Feel free to close this issue.

**Comment by will-in-wi** [comment]
The original version of this utility would create the cert, store it on the filesystem, and then email WebFaction support to have them install it. They later added API support to install the cert, which version 2 of this utility uses.

WebFaction (sorry if you already know this) uses frontend Nginx servers for https termination and reverse proxying. So we as users don't have access to install the cert or key. The only way to install the cert is through their API or their admin interface. Given that the point of Let's Encrypt is automation, I went for the automated option.

Does this make sense? Thanks for the question!

**Comment by Scott-MacD** [comment]
Yep, makes sense. I'm assuming renewing a certificate requires physically replacing the certificate as well correct? It doesn't just revalidate and continue using the same cert?

**Comment by will-in-wi** [comment]
Correct, a new cert is issued and installed. The expiration date on a cert is a property of the cert itself and is signed by the certificate authority (Let's Encrypt in this case) so that it cannot be change without modifying the cert, which would break the signature and would need to be re-signed.
